### ISSUE TITLE
Missing valid OSGi MANIFEST.MF when using Designer beta2 designs

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#8542] opened 2017-02-10 13:56 UTC
When trying to use components designed with Designer beta2 in an OSGi Liferay Portlet, it fails and returns the following stacktrace:

Caused by: java.lang.NoClassDefFoundError: com/googlecode/gentyref/GenericTypeReflector at com.vaadin.ui.declarative.DesignAttributeHandler.assignValue(DesignAttributeHandler.java:121) at com.vaadin.ui.AbstractComponent.readDesign(AbstractComponent.java:955) at com.vaadin.ui.CssLayout.readDesign(CssLayout.java:351) at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:526) at com.vaadin.ui.declarative.Design.designToComponentTree(Design.java:481) at com.vaadin.ui.declarative.Design.read(Design.java:584) at lu.technolink.users.design.components.PersonalInformationDesign.(PersonalInformationDesign.java:36) at lu.technolink.users.design.components.PersonalInformationDesignFacade.(PersonalInformationDesignFacade.java:11) at lu.technolink.users.form.components.PersonalInformationComponent.(PersonalInformationComponent.java:21) at lu.technolink.forms.UsersForm.(UsersForm.java:37) at vaadin.liferay.test.portlet.VaadinLiferayTestPortlet.init(VaadinLiferayTestPortlet.java:73) at com.vaadin.ui.UI.doInit(UI.java:738) at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:214) at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1462) ... 631 more

Looks like that library does not hold a valid OSGi MANIFEST.MF since it's not exporting the packages.

**Comment by Artur-** [comment] 2017-02-10 14:11
There is also no import statement for `com.googlecode.gentyref` in `vaadin-server`

**Comment by directdevice** [comment] 2017-03-07 15:02
It's a pity that such a simple issue hasn't been fixed yet and still open in 8.0.1 - shall I "contribute my first patch to a Vaadin project"?

**Comment by hesara** [comment] 2017-03-08 09:44
The real problem is that the official gentyref package in Maven Central does not have an OSGi manifest. Thus, we may need to publish our own distribution of it to resolve this.

**Comment by m1h43l** [comment] 2017-03-08 09:51
But not being able to change the manifest of gentyref should not be a show stopper to adjust the manifest of the Vaadin bundle as some servers have a convenient way of handling non-OSGi jars like Karaf : http://karaf.apache.org/manual/latest/#_wrap_deployer
Having a non-OSGi gentyref is no problem with Karaf (as the necessary entries are generated automatically) but atm the Vaadin bundle still needs to be patched manually.

**Comment by directdevice** [comment] 2017-03-08 11:44
@m1h43l, Vaadin shouldn't be sticked to Karaf either any other specific OSGi container implementation, in this regard, solution proposed by @hesara looks rational

**Comment by m1h43l** [comment] 2017-03-08 11:47
> Vaadin shouldn't be sticked to Karaf
... and that is not what I meant and not what I have written. I was refering to having the manifest of the Vaadin bundle adjusted has value even if the gentyref hasn't been adjusted.

**Comment by directdevice** [comment] 2017-03-08 12:07
Sorry, indeed! Wrapping of **gentyref** and shading **vaadin-server** bundle in order to adjust the manifest is the only one workaround I've found so far

**Comment by mstahv** [comment] 2017-03-08 12:46
Would it be hard to get rid of gentyref altogether? Or replace with some other library that behaves better.

**Comment by hesara** [comment] 2017-04-25 12:04
Effectively a duplicate of #8721

**Closed by hesara** 2017-04-25 12:04 UTC
Labels: bug
