### ISSUE TITLE
Sessions locked

### ISSUE THREAD

**Issue by aleuC** [vaadin/framework#12398] opened 2021-09-08 14:50 UTC
We have some Vaadin 7 applications with Vaadin PUSH.
The application server is IBM WAS, and we have a problem with the user session.
We talked to an IBM technician and this is his answer:

It seems that it is the application "AsynchronousProcessor.java" that is holding a lock. Try to move the com/vaadin/server/VaadinService.findVaadinSession above outside the lock, as a WAS session is already running synchronized (locked). The WAS session code itself would not cause the deadlock. Applications cannot synchronize session objects inside of the application because a deadlock with the session manager may occur. The deadlock occurs because the session manager does not expect the use of more than one locking mechanism.

--

at com/vaadin/server/WrappedHttpSession.getAttribute(WrappedHttpSession.java:54(Compiled Code))

          at com/vaadin/server/VaadinService.getSessionLock(VaadinService.java:587(Compiled Code))

          at com/vaadin/server/VaadinService.lockSession(VaadinService.java:613(Compiled Code))

          at com/vaadin/server/VaadinService.findOrCreateVaadinSession(VaadinService.java:666(Compiled Code))

          at com/vaadin/server/VaadinService.findVaadinSession(VaadinService.java:530(Compiled Code))

          at com/vaadin/server/communication/PushHandler.connectionLost(PushHandler.java:323)

          at com/vaadin/server/communication/PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:60)

          at org/atmosphere/cpr/AsynchronousProcessor.invokeAtmosphereHandler(AsynchronousProcessor.java:509)

             (entered lock: org/atmosphere/cpr/AtmosphereResourceImpl@0x00000000CF020D50, entry count: 1)

how can it be solved?

**Comment by TatuLund** [comment] 2021-09-08 17:08
Thanks for your report. Could you tell us which exact version you use.

Nevertheless, I think this is duplicate of https://github.com/vaadin/framework/issues/12352

**Comment by aleuC** [comment] 2021-09-09 07:12
Thanks, we are using Vaadin version 7.7.17

**Comment by TatuLund** [comment] 2021-09-23 05:22
Ok, that clearly indicates that the original issue you reported is fixed by the patch included in Vaadin 7.7.27.  And as I suspected it was indeed duplicate of the issue I linked. This new stack trace is about something completely different. You have not copied what exception happens there. 

But I see that something goes wrong when Vaadin tries to push changes to the browser. Is it IOException or something else?

https://github.com/vaadin/framework/blob/7.7/server/src/main/java/com/vaadin/server/communication/AtmospherePushConnection.java#L186

There is similar kind of stack trace here, not exactly the same path but quite close https://github.com/vaadin/framework/issues/8965

**Comment by TatuLund** [comment] 2021-09-23 05:48
More precisely, your new report may be duplicte of https://github.com/vaadin/framework/issues/7734

Which is partially fixed in Vaadin 7, but apparently can still occur in some form, as there is bug https://github.com/Atmosphere/atmosphere/issues/2311 in Atmosphere 2.2.13 used in Vaadin 7. Vaadin 8 uses newer version of Atmosphere that has this bug fixed. I cherry picked that fix to Vaadin 7 branch of Atmosphere, but it takes time for us to make a new build and release.

**Closed** 2021-11-16 08:08 UTC
Labels: duplicate, v7, BFP
