### ISSUE TITLE
ListSelect with single Selection in Vaadin 8.0.5

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9276] opened 2017-05-09 12:46 UTC
I need to have ListSelect with a single selection in Vaadin 8.0.5

Before with framework 7, I used listSelect.setMultiSelect(false) but it seems to not be available anymore.
How can I do now?

Thanks,

**Comment by Artur-** [comment] 2017-05-09 13:01
```
NativeSelect select = new NativeSelect();
select.setVisibleItemCount(5);
```

requires 8.1

**Comment by pinonpierre** [comment] 2017-05-09 13:08
Thanks for your answer.
What is the estimated date for the 8.1 version?

**Comment by Legioth** [comment] 2017-05-10 11:11
> What is the estimated date for the 8.1 version?

Currently making the last fixes before beta1. Schedule after that depends on the feedback we get based on the beta. We're assuming that the order of magnitude for the beta period would be one month.

Closing as duplicate of #9109.

**Closed by Legioth** 2017-05-10 11:11 UTC

**Comment by mvysny** [comment] 2020-05-29 13:46
There was a question from the customer just today whether it's possible to have a ListSelect with single select mode. Also this forum question: https://vaadin.com/forum/thread/15654622/vaadin-8-listselect-does-not-allow-anymore-single-selection

I think we should create a dedicated multi-select ListSelect component (which could perhaps simply extend `ListSelect` and set the number of visible items to 2).
