### ISSUE TITLE
Clearing binder fields should also remove the component error

### ISSUE THREAD

**Issue by krasnyt** [vaadin/framework#8997] opened 2017-04-01 21:28 UTC
When there are multiple fields binded to a binder, according to #8287 calling `binder.readBean(null)` should clear the fields - that works but the component errors remain and must be removed manually by calling `setComponentError(null)`.

Could clearing binder fields also remove component errors?

**Comment by Kalomo** [comment] 2019-03-14 11:16
We are facing the same issue and also want to have a better API to reset() or clear() the binder back to its initial state as described in #4780

**Comment by anasmi** [comment] 2019-03-29 07:45
Hi,

with this code running 8.7 I can't reproduce the problem : 
```
  Binder<Person> binder=new Binder<>();
                Person personTest=Person.createTestPerson1();
                TextField field=new TextField("Name");
                binder.forField(field).withValidator(name->name.length()>=4,
                        "Full name must contain at least three characters")
                        .bind(Person::getFirstName,Person::setFirstName);
                binder.setBean(personTest);
                Button reset=new Button("Reset Field",e->{
                       //binder.setBean(null);
                        binder.readBean(null);
                });
                Button validate=new Button("Validate", e->{
                        binder.validate();
                });
                addComponent(field);
                addComponent(reset);
                addComponent(validate);
```
Calling both `setBean` and `readBean` with null clears validation error message.  Have I missed something?  Also, method clearFields is calling `clearError` which sets the error to null using component you have mentioned 
You can check here the logic of  calling `setBean(null)` https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/Binder.java#L1653 
Or what components you are using?

**Comment by Kalomo** [comment] 2019-04-05 10:56
Hi,
thx for the reply. 
We were able to track down our issue and it was related to some reference issue and not to the bean binder at all. Everything else works fine  :)

**Comment by anasmi** [comment] 2019-04-05 11:09
Great to hear ! :) Thanks for letting us know :)

**Comment by anasmi** [comment] 2019-04-05 11:56
I will close this issue, as it's not reproducible anymore in the last version.  Please, create a new issue with the example code, if you encounter this problem under any other circumstances!

And thank you for your contribution! :)

**Closed by anasmi** 2019-04-05 11:56 UTC
Labels: BFP, bug, cannot reproduce, waiting for author
