### ISSUE TITLE
Grid resize rendering bug - disable RadioButton selected view

### ISSUE THREAD

**Issue by vVYou** [vaadin/framework#11911] opened 2020-03-05 16:25 UTC
Bug present in Vaadin Framework version 8.10.2 and previous versions as far as we can see.

When resizing a windows with a Grid that contains RadioButton as element the selection of the RadioButton is not rendered anymore.

To reproduce see the following UI code :

```
@Override
protected void init(VaadinRequest request) {
	List<Item> content = Arrays.asList(new Item(true), new Item(true), new Item(false));

	Grid<Item> grid = new Grid<>(DataProvider.ofCollection(content));
	grid.setSizeFull();
	grid.setSelectionMode(Grid.SelectionMode.NONE);
	grid.setBodyRowHeight(70);
	grid.addComponentColumn(this::radioButtonResponse).setCaption("Boolean");

	setContent(grid);
}

private RadioButtonGroup<Boolean> radioButtonResponse(Item item) {
	RadioButtonGroup<Boolean> yesNoRadioButtonGroup = new RadioButtonGroup<>();
	yesNoRadioButtonGroup.setItems(Boolean.TRUE, Boolean.FALSE);
	yesNoRadioButtonGroup.setSelectedItem(item.isBool());
	return yesNoRadioButtonGroup;
}

private class Item {
	boolean bool;

	public Item(boolean bool) {
		this.bool = bool;
	}

	public boolean isBool() {
		return bool;
	}
}
````

When the screen is rendered :
![GridBugBeforeResize](https://user-images.githubusercontent.com/5763558/76001787-ee8e4d80-5f05-11ea-94d8-867dd6910eca.PNG)

After resizing the window :
![GridBugAfterResize](https://user-images.githubusercontent.com/5763558/76001776-ecc48a00-5f05-11ea-985c-6ebb96c7f5c1.PNG)

**Comment by TatuLund** [comment] 2020-03-06 06:34
This could be related to or duplicate of https://github.com/vaadin/framework/issues/11877

**Comment by TatuLund** [comment] 2020-03-06 07:48
The workaround is to use some mechanism that forces deep redrawing of that column when Browser is resized. One approach is to remove and add the column:

```
public class MyUI extends UI {

	Grid<Item> grid = null;
	private Registration registration;
	private Column<Item, RadioButtonGroup<Boolean>> column;
	
	@Override
	protected void init(VaadinRequest request) {
		List<Item> content = Arrays.asList(new Item(true), new Item(true), new Item(false));

		grid = new Grid<>(DataProvider.ofCollection(content));
		grid.setSizeFull();
		grid.setSelectionMode(Grid.SelectionMode.NONE);
		grid.setBodyRowHeight(70);
		column = grid.addComponentColumn(this::radioButtonResponse).setCaption("Boolean");

		setContent(grid);
	}

	@Override
	public void attach() {
		super.attach();
		registration = getPage().addBrowserWindowResizeListener(event -> {
			grid.removeColumn(column);
			column = grid.addComponentColumn(this::radioButtonResponse).setCaption("Boolean");
		});
	}
	
	@Override
	public void detach() {
		registration.remove();
		super.detach();
	}
	
	private RadioButtonGroup<Boolean> radioButtonResponse(Item item) {
		RadioButtonGroup<Boolean> yesNoRadioButtonGroup = new RadioButtonGroup<>();
		yesNoRadioButtonGroup.setItems(Boolean.TRUE, Boolean.FALSE);
		yesNoRadioButtonGroup.setSelectedItem(item.isBool());
		return yesNoRadioButtonGroup;
	}

	private class Item {
		boolean bool;

		public Item(boolean bool) {
			this.bool = bool;
		}

		public boolean isBool() {
			return bool;
		}
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)    
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by Ansku** [comment] 2020-03-23 12:29
I don't want to add the experimental fix into the framework itself because it's ugly and contains API changes and I don't want to be stuck with those API changes forever (I'm convinced there has to be a better way to do this, but I haven't found it yet). Instead, there is now an add-on that extends ComponentRenderer that you can use instead if you don't want to go the remove-and-replace route proposed earlier: https://vaadin.com/directory/component/refreshcomponentrenderer-add-on/

**Closed** 2021-02-12 08:56 UTC
Labels: BFP, wontfix, workaround
