### ISSUE TITLE
Grid Editor doesn't adjust the field widths with the column widths

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10764] opened 2018-03-28 03:54 UTC
If you change the width of a column it's not reflected in the editor. This causes the columns to all be out of alignment with the row being edited. In some cases such as when a column is too small and you try to widen it then the only way to resolve this is to cancel and start again.

That being said if you adjust the fields enough you can actually see the values below the edited row which makes for an odd interface...

**Comment by TatuLund** [comment] 2018-04-02 07:59
Duplicate of https://github.com/vaadin/framework/issues/7276

**Closed by TatuLund** 2018-04-02 07:59 UTC
Labels: duplicate

**Comment by FollowSteph** [comment] 2018-04-02 08:15
That issue is marked as stale and is 2.5 years old. Are there any plans on fixing it?
