### ISSUE TITLE
CheckBoxGroup selectall please?

### ISSUE THREAD

**Issue by amahdy** [vaadin/framework#9481] opened 2017-06-05 11:19 UTC
```java
        CheckBoxGroup<Person> xyz = new CheckBoxGroup<>();
        xyz.setItems(service.getEntries());
        xyz.deselectAll(); //OK
        xyz.selectAll() // No luck :'(
```

**Comment by pleku** [comment] 2017-11-03 11:45
duplicate of #9307

**Closed by pleku** 2017-11-03 11:45 UTC
Labels: enhancement
