### ISSUE TITLE
Combobox Valuechange Bug

### ISSUE THREAD

**Issue by Vilkaz** [vaadin/framework#10660] opened 2018-02-26 13:19 UTC
- Vaadin Framework version : Vaadin Version 8.3
- Browser version : Chrome Version 59.0.3071.115 
- Description of the bug : 
Something is not working correctly when The Combobox valueChangeEvent is not userOriginated.

1 set the value in an ComboBox.
2 change the value with event from another component 
(like another button.addClickListener(e -> changeComboboxValue())
3 try to set the SAME value again by WRITING ! not Selecting ! 
4 When you leave the ComboBox with Tab, the written Value is not taken as actual value. It si overwritten by the not user Originated value.
- Minimal reproducible example

i actualy wrote a little project with 2 clases for it. but i cant uploade it to github

```
public class Pojo {
    int number;
    public Pojo(int number) {
        this.number = number;
    }
    public int getNumber() {
        return number;
    }
    public void setNumber(int number) {
        this.number = number;
    }
}
```

```
package de.vilkas.comboBoxBugTest;

import com.vaadin.data.Binder;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.ui.ContentMode;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.*;

import java.util.Arrays;

@SpringUI
public class BugTest extends UI {

    private Pojo pojo;

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        Binder<Pojo> binder = new Binder<>();
        ComboBox<Integer> numbers = new ComboBox<>();
        numbers.setItems(Arrays.asList(0, 1, 2, 3));
        binder.forField(numbers)
                .bind(Pojo::getNumber, Pojo::setNumber);

        pojo = new Pojo(1);
        binder.setBean(pojo);

        Button reset = new Button("reset");
        reset.addClickListener(e -> {
            pojo.setNumber(0);
            binder.setBean(pojo);
        });

        Button tellMeTheValue = new Button("show values");
        tellMeTheValue.addClickListener(e -> {
            Notification.show("BeanValue = " + pojo.getNumber() + "\ncomboboxValue = " + numbers.getValue());
        });


        HorizontalLayout buttons = new HorizontalLayout(numbers, tellMeTheValue, reset);
        Label instruction = new Label("1: Enter not null Value (1-3)" +
                "\n2: Click the reset button (ComboboxValue goes to 0)" +
                "\n3: Click IN the combobox, and enter the previous (!!!) value by HAND ! (not selecting with mouse from the dropDown Menu)" +
                "\n4: Click TAB to switch from the Combobox to the 'show Values' button. The value from Combobox will be resetet to 0. If you enter OTHER Value then the previous, then everything is working fine.",
                ContentMode.PREFORMATTED);

        VerticalLayout mainLayout = new VerticalLayout(buttons, instruction);
        setContent(mainLayout);
    }
}
```

- Expected behavior  after entering the value and leaving the combobox, the new written value has to be applied to bean and combobox.
- Actual behavior the old value stays

**Comment by anasmi** [comment] 2018-02-26 13:25
Hi,
your issue sound like this one: https://github.com/vaadin/framework/issues/10284
What version do you have in use exactly? 8.3.0 or 8.3.1? Could you reproduce the problem using 8.3.1 also?

**Comment by Vilkaz** [comment] 2018-02-26 13:47
it was in 8.3.0 so i tried 8.3.1. but it is still there (after mvn clean package and server reboot)
`<vaadin.version>8.3.1</vaadin.version>`

sadly no difference :/

i made a small project with only this bug, i just cant upload it from my Work (security :)
but if you take those 2 classes (Pojo and View) you can reproduce it quite fast :)

**Comment by anasmi** [comment] 2018-02-27 11:14
Hi,
I was also able to reproduce this issue.
I will add here for reference a simplified example of how to reproduce the problem (based on the example above):

```
    @Override
    protected void init(VaadinRequest vaadinRequest) {

        ComboBox<Integer> numbers = new ComboBox<>();
        numbers.setItems(Arrays.asList(0, 1, 2, 3));

        Button reset = new Button("reset");
        reset.addClickListener(e -> {
            numbers.setValue(0);});

        HorizontalLayout buttons = new HorizontalLayout(numbers, reset);
        Label instruction = new Label("1: Enter not null Value (1-3)" +
                "\n2: Click the reset button (ComboboxValue goes to 0)" +
                "\n3: Click IN the combobox, and enter the previous (!!!) value by HAND ! (not selecting with mouse from the dropDown Menu)" +
                "\n4: Click TAB to switch from the Combobox to the 'show Values' button. The value from Combobox will be resetet to 0. If you enter OTHER Value then the previous, then everything is working fine.",
                ContentMode.PREFORMATTED);

        VerticalLayout mainLayout = new VerticalLayout(buttons, instruction);
        setContent(mainLayout);
    }

```

**Comment by Ansku** [comment] 2018-02-27 14:42
Which version are you using? This should be fixed in the newest 8.3 release already.

**Comment by Vilkaz** [comment] 2018-02-28 07:29
i tested it with 8.3.0  and with 8.3.1 

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<vaadin.version>8.3.1</vaadin.version>

And it was written in the issue.

You have the code to reproduce it, this is an active bug. 

What else can we do, to make you test it before you close it :) ?

**Comment by Ansku** [comment] 2018-02-28 10:34
I did in fact test it before I closed the issue, using both versions of the code presented here, and couldn't reproduce the problem. I tried it again just now with the initial code example, just in case I missed something, but I still can't reproduce it. I don't have access to that exact version of Chrome, but with 64.0.3282.186 on Windows 7 it seems to work just fine. Are you sure it's not a cache issue? Chrome can sometimes be a bit too clingy.

Steps I used:
* initial selection 1, click reset -> switched to 0
* focus ComboBox input area, type "1", tab out -> stays as 1

and:
* select 2, click out -> stays as 2
* click reset -> switched to 0
* focus ComboBox input area, type "2", tab out -> stays as 2

At every phase of the test clicking "show values" gives matching value for bean and combobox.
Did I misunderstand something about the instructions?

**Comment by Vilkaz** [comment] 2018-02-28 14:37
the second Part is different in my case.

If you don't mind, i would test it on second mashine at home, and then make short video / upload it as "protected" on youtube ?

We only found this bug while automated surface testing with Tosca, which enters values without humanly clicking.

It is not critical, but a few specific tests are red now ... :)

That's why im ready to invest some time to help you find this, aspecialy if it looks, like it was allready solved :) ! 

Please give me 24h to uploade "video prove" :D

**Comment by Ansku** [comment] 2018-02-28 15:33
If we can figure out how to reproduce this we can look into fixing it, absolutely. This used to be easily reproducible on my computer in an earlier version, but the previous fix took care of that and I haven't seen it since.

**Comment by Vilkaz** [comment] 2018-02-28 19:37
i found the difference.

it's the new step 2.

(The bug does not happen, if you click onto reset imideatly after chosing value.... rare bug :)

1: Enter not null Value (1-3)
**2: Click Tab or somewhere else (lose focus, but don'T click on Reset Button as first !)**
3: Click the reset button (ComboboxValue goes to 0)
4: Click IN the combobox, and enter the previous (!!!) value by HAND ! (not selecting with mouse from the dropDown Menu)
5: Click TAB to switch from the Combobox to the 'show Values' button. The value from Combobox will be resetet to 0. If you enter OTHER Value then the previous, then everything is working fine.
 If you click the reset button as step 2, the value fast switches to zero and then to the corect Value, looks like that fix you was talking about ;) !

Demo on Heroku (its free plan, i hope it is still up and not "Sleeping")
https://comboboxtest.herokuapp.com/

Repo
https://github.com/Vilkaz/Comboboxbug

**Comment by Ansku** [comment] 2018-03-01 17:30
I actually already tested that without clicking reset right away, but I finally figured out what the difference is -- the first value also needs to be _written_, not selected. It was so heavily specified in that later stage that I didn't come to think it might be necessary for the first step as well.

**Closed** 2018-03-08 12:04 UTC

**Comment by Vilkaz** [comment] 2018-03-08 18:40
thank you very much :) ! 👍
