### ISSUE TITLE
DetailsGenerator shows in wrong place when Vertical scrollbar is required

### ISSUE THREAD

**Issue by evanzel** [vaadin/framework#11302] opened 2018-11-09 08:33 UTC
Since Framework version 8.5.1 when the details generator produces a component that causes a vertical scrollbar to appear in the grid, details are shown in the wrong place and only a resizing of the window fixes the issue.

minimal code to reproduce the issue is provided:
```
   final VerticalLayout layout = new VerticalLayout();
        List items = new ArrayList();
        for (int i = 0; i < 2; i++) {
            items.add(("#" + i));
        }
        Grid<String> grid = new Grid(null, items);
        grid.setHeight("300px");
        grid.addColumn(t -> {
            return t;
        });
        grid.getEditor().setEnabled(false);
        grid.setDetailsGenerator((String t) -> {
            VerticalLayout vl = new VerticalLayout(new Label("item: " + t));
            vl.setHeight("310px");
            return vl;
        });
        grid.addItemClickListener(listener -> {
            grid.setDetailsVisible(listener.getItem(), !grid.isDetailsVisible(listener.getItem()));
        });
        layout.addComponents(grid);
        setContent(layout);
```

**Comment by evanzel** [comment] 2018-11-20 08:42
Adding steps to reproduce:
Click on item#0  to show details
Details will be shown below the item#1 instead of item#0
Click again item#0 to hide details
Details are hidden and item#1 is nowhere to be seen

**Comment by evanzel** [comment] 2018-11-21 13:49
PR https://github.com/vaadin/framework/pull/11326 seems to be a fix for this issue too.

**Comment by TatuLund** [comment] 2018-11-25 08:59
This is duplicate of https://github.com/vaadin/framework/issues/11325

**Closed by TatuLund** 2018-11-25 08:59 UTC
Labels: duplicate
