### ISSUE TITLE
The checkbox cannot be selected (checked) in IE version 11.966.15063

### ISSUE THREAD

**Issue by AdamGasior** [vaadin/framework#10792] opened 2018-04-05 13:40 UTC
- Vaadin Framework version 7.6.5
- Browser version
- Web container name and version Java EE
- Description of the bug
- Minimal reproducible example
- Expected behavior
- Actual behavior

The checkbox cannot be selected (checked) in IE version 11.966.15063

The issue can be reproduced by accessing Vaadin Sampler:  https://demo.vaadin.com/sampler-77/#ui/data-input/other/check-box

**Comment by TatuLund** [comment] 2018-04-05 14:00
Could this be duplicate of this one: https://github.com/vaadin/framework/issues/5361

**Comment by sergey-vaadin** [comment] 2018-04-10 08:16
In these threads there are various solutions mentioned related to removing Pragma: no-cache from HTTP headers. Would one of these be an option for you?
https://stackoverflow.com/questions/22670026/font-awesome-with-https/30259640#30259640
https://stackoverflow.com/questions/9102185/internet-explorer-font-face-ssl/43093451#43093451
https://stackoverflow.com/questions/31745307/ie-11-sometimes-preventing-the-display-of-font-awesome-webfonts

**Comment by AdamGasior** [comment] 2018-04-10 09:48
Hi Sergey,

I checked the links.  The first solution looks promising (first link).

Is it enough to add web.xml:
<filter>
    <filter-name>NoCacheHeaderFilter</filter-name>
    <filter-class>NoCacheHeaderFilter</filter-class>
    <init-param>
        <param-name>exclude</param-name>
        <param-value>^/(image|css|js|fonts|lib|partials)/.*</param-value>
    </init-param>
</filter>


Regards,

Adam Gasior
MES Application Architect

**Comment by sergey-vaadin** [comment] 2018-04-10 09:57
Hi Adam, 
yes, together with the filter class from the second code snippet. I can try to check that too.

**Comment by AdamGasior** [comment] 2018-04-10 09:59
But there should I add the filter class if I use Vaadin CDI servlet?

Regards,

Adam Gasior
MES Application Architect

**Comment by AdamGasior** [comment] 2018-04-10 10:02
Hi Sergey

I the changes in web.xml are clear for me, adding the filter class is confusing for me. Could you test and try it yourself where to add the changes and if they will solve the issue.

Regards,

Adam Gasior
MES Application Architect

**Comment by sergey-vaadin** [comment] 2018-04-10 10:07
Adam,
filter class could be added anywhere to the classpath visible to servlet container, i.e. into the application code. <filter-class>NoCacheHeaderFilter</filter-class> in this case is fully qualified name, better example would be <filter-class>com.example.NoCacheHeaderFilter</filter-class> This class will be initialized and run by the servlet container.

**Comment by AdamGasior** [comment] 2018-04-10 10:11
Hi Sergey,

Still not clear for me

What should i do with that piece of code:
    if (null != exclude) {
        HttpServletRequest httpRequest = (HttpServletRequest) request;
        HttpServletResponse httpResponse = (HttpServletResponse) response;

        String context = httpRequest.getContextPath();
        String path = httpRequest.getRequestURI().substring(context.length());
        if (!exclude.matcher(path).matches()) {
            httpResponse.setHeader("Pragma", "no-cache");
            httpResponse.setHeader("Cache-Control", "private, max-age=0, no-store, no-cache");
            httpResponse.setDateHeader("Expires", System.currentTimeMillis());
        }
    }

    chain.doFilter(request, response);

**Comment by AdamGasior** [comment] 2018-04-10 10:12
Coul we have 15 min Skype call to clarify that?


Regards,

Adam Gasior
MES Application Architect

**Closed** 2018-08-27 18:27 UTC
Labels: BFP, bug, v7
