### ISSUE TITLE
ComboBox not clear when DataProvider is empty

### ISSUE THREAD

**Issue by dkononenko** [vaadin/framework#10468] opened 2017-12-23 05:59 UTC
Hello!
ComboBox doesn’t display correct value (empty string) after setValue(null) if its dataprovider is empty
Vaadin Framework version 8.1.7, 8.2.0

```java
package com.example.demo;

import com.vaadin.data.provider.DataProvider;
import com.vaadin.server.VaadinRequest;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.UI;

import java.util.ArrayList;
import java.util.List;

class Foo {
    public Foo(String name, List<Bar> barList) {
        this.name = name;
        this.barList = barList;
    }

    public String getName() {
        return name;
    }

    public List<Bar> getBarList() {
        return barList;
    }

    private String name;
    private List<Bar> barList;
}

class Bar {
    public Bar(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    private String name;
}

@SpringUI
public class AppUI extends UI {
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        List<Foo> fooList = new ArrayList<>();
        fooList.add(new Foo("foo1", new ArrayList<Bar>() {{
            add(new Bar("bar_1_1"));
            add(new Bar("bar_1_2"));
            add(new Bar("bar_1_3"));
        }}));

        fooList.add(new Foo("foo2", new ArrayList<>()));

        fooList.add(new Foo("foo3", new ArrayList<Bar>() {{
            add(new Bar("bar_3_1"));
            add(new Bar("bar_3_2"));
        }}));


        ComboBox<Bar> comboBox2 = new ComboBox<>();
        comboBox2.setItemCaptionGenerator(Bar::getName);

        ComboBox<Foo> comboBox1 = new ComboBox<>();
        comboBox1.setEmptySelectionAllowed(false);
        comboBox1.setItemCaptionGenerator(Foo::getName);
        comboBox1.setDataProvider(DataProvider.ofCollection(fooList));
        comboBox1.addValueChangeListener(e -> {
            List<Bar> list = e.getValue().getBarList();
            comboBox2.setDataProvider(DataProvider.ofCollection(list));
            comboBox2.setValue(list.stream().findFirst().orElse(null));
        });


        setContent(new HorizontalLayout(comboBox1, comboBox2));
    }
}
```

![default](https://user-images.githubusercontent.com/5399327/34317470-32db563a-e7d1-11e7-86ed-27995295cacf.gif)

**Comment by simon-chromow** [comment] 2017-12-28 08:20
Duplication of [#9047](https://github.com/vaadin/framework/issues/9047)

**Comment by tsuoanttila** [comment] 2018-04-09 08:12
Closing as duplicate of #9047.

**Closed by tsuoanttila** 2018-04-09 08:12 UTC
Labels: duplicate
