### ISSUE TITLE
Grid Select all does ignore filtering

### ISSUE THREAD

**Issue by imsandli** [vaadin/framework#10595] opened 2018-02-02 09:21 UTC
### Description of the bug
On a filterable grid with Selection Mode Multi, the select all checkbox does ignore the filtering and all items are selected, even if they are not visible.

Consider a User wants to delete some entries from a grid starting with the same prefix. He adds a filter, press select all and then the delete Button.

grid.getSelectedItems() will return all items as they were selected invisible for the user. With this behaviour the user may accidentaly remove all his data.

### Expected behaviour
select all does only select the visible items.

### Reproduction
- Open [Sampler](https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features)
- Switch Selection Mode to `Multi`
- Filter company for `Deom` -> there are two entries (Deomic and Deominose)
- Press select all checkbox on top left.
- Remove company filter
- Now all items are select instead of the expected (Deomic and Deominose)

### Vaadin Framework version
8.3.0

**Comment by TatuLund** [comment] 2019-12-06 20:13
This is duplicate of https://github.com/vaadin/framework/issues/11479

**Comment by TatuLund** [comment] 2019-12-06 20:14
Should be fixed since Vaadin 8.9.0 by https://github.com/vaadin/framework/pull/11790

**Closed by TatuLund** 2019-12-06 20:14 UTC
