### ISSUE TITLE
Vaadin Grid selection column indicating "..." in cell anytime with newest Chrome version

### ISSUE THREAD

**Issue by jbreitung** [vaadin/framework#12068] opened 2020-08-10 10:18 UTC
Hi there,

since updating to **Vaadin 8.11.x** I am experiencing issues with the rendering of the **Vaadin Grid** in my UI when using the newest version of Google Chrome. Most of the time I am using the **MultiSelectionModel** for selection. 

In current versions the grid is displaying "..." in the cells (near the embedded checkbox), which is normally just indicated if the cells size is to small to display the complete content.

In previous releases it was never necessarry to specify the size of the "selection"-column (column index 0) because it is always used by the selection model to display a checkbox for selecting multiple entities.

You can see it in the following screenshot taken in Google Chrome: 

![Screenshot_20200810_121407](https://user-images.githubusercontent.com/22149422/89772871-0f854b00-db03-11ea-95ab-81044e647768.png)

The selection model is always assigned in the same procedure:

```
Grid<Entity> grid = new Grid<>();
grid.setSizeFull();

grid.setDataProvider(dataProvider);

selectionModel = (MultiSelectionModel<Entity>) grid.setSelectionMode(Grid.SelectionMode.MULTI);
dataProvider.setSelectionModel(selectionModel);
```

Currently I was testing it with Google Chrome Version 84.0.4147.105
With Mozilla Firefox 78.1.0esr the issue does not exist.

For me it looks like a small bug of the Grid in combination with the newest Google Chrome version... Please correct me if I am wrong.

Thanks!

**Comment by TatuLund** [comment] 2020-08-10 11:20
I think this is duplicate of https://github.com/vaadin/framework/issues/12048

**Closed** 2020-08-30 08:22 UTC
Labels: duplicate
