### ISSUE TITLE
Change Renderer of existing Grid column

### ISSUE THREAD

**Issue by ssindelar** [vaadin/framework#8703] opened 2017-02-27 15:12 UTC
In Vaadin 8 it seems you can't change the Renderer after the column is created. This is quite annoying if you use the `Grid(Class<T> beanType)` constructor. All the columns get auto generated with a simple TextRenderer. If you need to set the Renderer in just one column you need to use the `Grid()` constructor and add all columns manually.

This is especially annoying because the Renderers are the defacto replacement of the Converters from Vaadin 7. So if the default rendering of just one type is not correct (which is true for all complex objects) you need to add all columns manually.

**Comment by Legioth** [comment] 2017-02-28 07:54
Duplicate of https://github.com/vaadin/framework/issues/8250

**Closed by Legioth** 2017-02-28 07:54 UTC
Labels: candidate
