### ISSUE TITLE
ComboBox occasionally shows browser's AutoFill options

### ISSUE THREAD

**Issue by juhawilppu** [vaadin/framework#10373] opened 2017-11-24 10:50 UTC
Sometimes when the user clicks on the arrow to show the answer options, the list contains a random option that comes from the browser. It reproduces very rarely and randomly, but we have seen it many times. It's only visible once meaning that it disappears if you close the list and re-open it.

Tested with Vaadin 8.1.6 using Google Chrome.

See example:
The first option, "Human", is not part of the answer options that were given in comboBox.setItems(list). Instead, it was written to some totally different textfield and randomly pops up from the Google Chrome's AutoFill feature.

![combobox_bug](https://user-images.githubusercontent.com/1705197/33207322-e26f638e-d115-11e7-9b21-81c7f0294f48.png)

**Comment by Artur-** [comment] 2017-11-24 10:51
Related to or same as #7820

**Comment by fhasenclever** [comment] 2017-12-07 22:07
Try to disable AutoFill in Google Chrome.
I had a similiar issue

**Comment by hoerup** [comment] 2018-05-08 09:17
This bug is still present in 8.4.1

**Comment by FollowSteph** [comment] 2018-11-10 02:19
I know it's related to 7820 but it's still an issue in that eventually some of the random numbers values will match other random values in the browser...

**Comment by TatuLund** [comment] 2019-05-16 12:42
This seems to be duplicate of https://github.com/vaadin/framework/issues/11437, which is fixed.

**Closed by TatuLund** 2019-05-16 12:42 UTC
Labels: duplicate
