### ISSUE TITLE
HTML in description of MenuItem

### ISSUE THREAD

**Issue by vt512** [vaadin/framework#9928] opened 2017-09-04 11:40 UTC
Vaadin 8.1.3

I want to add some HTML formatted Text as Tooltip of a MenuItem.
A method setDescription(String description, ContentMode mode) as in AbstractComponent is not available in MenuItem.
Could you please add it?

Some example Code:

```
@SpringUI(path = "ui")
public class MyUI extends UI {
    protected void init(VaadinRequest request) {
        final MenuBar menuBar = new MenuBar();
        final MenuBar.MenuItem menuItem = menuBar.addItem("bla", item -> Notification.show("bla"));
        menuItem.setDescription("my <b>html</b> description" /*, ContentMode.HTML */);

        final Label label = new Label("bla");
        label.setDescription("my <b>html</b> description" , ContentMode.HTML);

        final VerticalLayout vl = new VerticalLayout(
                menuBar,
                label
        );

        setContent(vl);
    }
}
```

**Comment by hesara** [comment] 2017-09-04 12:20
Duplicate of #8591.

**Closed by hesara** 2017-09-04 12:20 UTC
