### ISSUE TITLE
TabSheet tabpanel is not resized properly

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#11124] opened 2018-08-21 10:01 UTC
- Vaadin Framework 8.5.1
- Seems to be browser / OS independent (tested on Windows 10 with latest Chrome, FF and IE11)

- Description of the bug
The bug only occurs with a quite specific set of layouts (see sample project). What happens is that when the browser window is resized horizontally, the `<div role="tabpanel" class="v-tabsheet-content">` element does not react to the changed width. However, when a server round trip has completed (eg. click a button that shows a notification), the tabpanel will snap back to the correct size. 

- Expected behavior
Resizing the browser window should also refresh the TabSheet's contents' size. 

Note that there are some workarounds to the issue; one of them is having a BrowserResizeListener that does `UI.getCurrent().markAsDirty();` in the handler. Another workaround is using a different root-level layout (VerticalLayout instead of CssLayout).

Sample project to reproduce the issue: 
[v8-tabsheet-resize-bug.zip](https://github.com/vaadin/framework/files/2305492/v8-tabsheet-resize-bug.zip)

**Comment by Ansku** [comment] 2018-08-30 13:01
Changing the default behaviour would be detrimental for performance (which is CssLayout's main feature), and the issue is easy to work around for the use cases where it's needed, so I'll close this ticket. See the (likewise closed) pull request for more workaround options.

**Closed by Ansku** 2018-08-30 13:01 UTC
Labels: BFP, wontfix
