### ISSUE TITLE
TreeGrid filter IndexOutOfBoundsException

### ISSUE THREAD

**Issue by playa92** [vaadin/framework#11431] opened 2019-01-22 13:30 UTC
- Vaadin 12.04
- Google Chrome v. 71.0.3578.98

Hi everyone,
I'm using a TreeGrid with filtering but in case of no match, I throw this exception.

![schermata da 2019-01-22 14-13-15](https://user-images.githubusercontent.com/22664214/51538655-2cd7c300-1e52-11e9-8b68-fa53e78c9d14.png)
![schermata da 2019-01-22 14-11-24](https://user-images.githubusercontent.com/22664214/51538661-2f3a1d00-1e52-11e9-8580-8a68b9024529.png)

OUTPUT:
![schermata da 2019-01-22 14-14-23](https://user-images.githubusercontent.com/22664214/51538671-35c89480-1e52-11e9-8a12-971e85e14c30.png)

**Comment by TatuLund** [comment] 2019-01-22 13:32
As this is issue in TreeGrid of Vaadin Platform V12+, the issue should be transferred here: https://github.com/vaadin/vaadin-grid-flow

**Comment by TatuLund** [comment] 2019-01-22 13:33
The issue is already reported in https://github.com/vaadin/vaadin-grid-flow/issues/464

**Closed by TatuLund** 2019-01-22 13:33 UTC
Labels: invalid
