### ISSUE TITLE
BeanValidationBinder says the form is valid even though required (@NotNull) field is not filled

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#9000] opened 2017-04-03 10:30 UTC
Vaadin 8.0.5

Example code to reproduce

    public static class Entity {

        @NotNull
        private String name;

        public void setName(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        @Override
        public String toString() {
            return "Entity, name: " + name;
        }

    }

    final TextField name = new TextField();

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        name.setCaption("Type your name here:");

        Entity entity = new Entity();
        Binder<Entity> b = new BeanValidationBinder<>(Entity.class);
        b.bindInstanceFields(this);

        b.setBean(entity);

        Button button = new Button("Check validity");
        button.addClickListener(e -> {
            ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
            Validator validator = factory.getValidator();
            Set<ConstraintViolation<Entity>> validate = validator.validate(entity);
            String msg = String.format("Binder.isValid: %s, JSR 303 valid: %s", b.isValid(), validate.isEmpty());
            Notification.show(msg);
        });

        layout.addComponents(name);
        layout.addComponent(button);

        setContent(layout);
    }

**Comment by viydaag** [comment] 2017-08-25 15:59
I might know why the @NotNull does not work on TextField. With new data binding API, TextField value cannot be null. It is always empty at the begining. So as a workaround, adding the @Size(min=1) does the trick.

**Comment by tsuoanttila** [comment] 2017-09-04 08:35
Indeed the default "null representation" in the case of TextField is one-way change only. There was a long discussion on wether it should change `null -> "" -> null` or not. If you want to use `NotNull`, you should use `binder.forField(textField).withNullRepresentation("")` which performs the change back from empty string to `null`. However this will mean that if the user actually tries to input an empty string, they really can't.

**Comment by viydaag** [comment] 2017-09-04 18:05
Thx for the precision

**Comment by jcgueriaud** [comment] 2017-12-08 09:22
I tried to fix this issue but I think it will break some stuff (it does fix NotNull issue but may break NotEmpty or Size min). And there are some differences between withNullRepresentaiton and the "default null representation" that I'm not sure to understand.

I'm not quite sure if it's possible to have exactly the "validation" between BeanValidator and JSR303 validation because of null representation. (but I think Vaadin validation should never be ok if JSR303 is not).

Perhaps a simple solution is to change setRequiredIndicator to asRequired. The BeanValidationBinder will required a default required message but the behaviour is more as expected (in my opinion).
It will work for NotNull, Size min or NotEmpty and if someone don't want this behaviour he can default required behaviour for one annotation.

**Comment by mstahv** [comment] 2017-12-08 11:01
Thanks @jcgueriaud, this really needs to be solved somehow. Too bad the null representation is still an issue :-( Maybe the default values like empty string should be passed to the bean when doing the binding. This wouldn't fix all oddities, but at least the most major one (JSR303 validation does not match "vaadin validation").

**Comment by jcgueriaud** [comment] 2017-12-13 14:19
My "patch" is not better (it's worse) because it does break some stuff and does not correct the oddity.
null is represented differently in the UI than in the backend. It may be converted in one way (default nullrepresentation) or two-way (custom). (if I understand it correctly).
And without JSR303, there is "asRequired" method for that (we don't use validator for that).
So is it really possible to try to solve the "JSR303 required" fields using a Validator ?

Should it be fix by using asRequired (and losing the custom message) ?

Any ideas ?

**Comment by micpalmia** [comment] 2018-02-11 22:04
> Maybe the default values like empty string should be passed to the bean when doing the binding

@mstahv yes, most definitely yes. 

If the issue is the fact that `TextField`s are really never `null`, this should be reflected back to the Bean when doing the binding. I would expect that the (unbuffered) binder would keep bean and form fields constantly in sync, without masking magic null/empty string conversions. Otherwise, we get a `Binder` saying it's all good, while a `Validator` on the same Bean is rightfully full of broken constrains!

**Comment by mstahv** [comment] 2018-05-07 10:00
Just verified that the issue is still in Vaadin 10 beta9 as well. Would be really nice to get this sort of issues fixed for 10.

**Comment by Legioth** [comment] 2018-05-18 15:37
`@NotNull` on a field bound to a `TextField` is indeed a slightly weird situation since its `getValue()` will never return `null`. There are thus two alternative ways interpretations of the situation.

1. `@NotNull` is on the bean not for the sake of `Binder` and the `UI`, but only to protect the database. This means that the original `""` value should pass validation and that the field should not be marked as required. For this to work, it also requires `""` to be explicitly written to the bean in case the value there is `null` even if the field has not been modified according to `Binder`.
2. `@NotNull` is accidentally used instead of e.g. `@Size(min = 1)` or `@NotEmpty` with the intent that the field should indeed be required. In this case, there would have to be an explicit "backup" validator that would catch the `""` case that would pass `@NotNull`.

The current implementation is thus bad in different ways for both cases. We should pick one of the cases as the default and offer a way of choosing the other.

My suggestion would be to change `RequiredFieldConfigurator` so that we also pass either the field instance or the field's default value to it and change the default so that `@NotNull` only marks the field as required if it's default value is `null`. Correspondingly, the `@NotEmpty` and `@Size(min = 1)` implementations should only make the field required if the default value is a `String` or `Collection`. On top of this, we should also implement the explicit writeback of values that are modified when passed through the chain. I don't we should implement an automatic `isEmpty()` fallback validator for the opposite case, but instead encourage developers to do an explicit `setNullRepresentation("")` which would cause `""` from the field to be written back as `null` to the bean.

**Comment by Legioth** [comment] 2018-05-18 18:43
To be fixed in Flow by https://github.com/vaadin/flow/pull/4138 and https://github.com/vaadin/flow/pull/4139.

I'll leave it to @tsuoanttila and/or @elmot to determine whether these patches should be picked to 8.x. The first patch is API compatible but changes an assumption that a unit test depends on. The second changes a relatively rarely used API and also requires some test adjustments.

**Comment by Legioth** [comment] 2018-05-21 07:54
How would a binder-wide default null representation work in practice?

I can come up with two different alternatives.
1. Allow changing the default automatic null representation to be two-way instead of only for model -> presentation conversions, e.g. `binder.setTwoWayNullRepresentation(true)`.
2. Make it possible to set a default null representation value other than the field's `getEmptyValue()`. This would have to be done per field type (e.g. `AbstractTextField` or field type type (e.g. `String`) (which is not always knowable because of type erasure). This could be something like `binder.setDefaultNullRepresentation(AbstractTextField.class, "");`. One might then wonder whether this mechanism for configuring defaults for a specific field type should be limited to only null representations, or if it should be a slightly more generic hook that is run before returning from a matching `forField(fieldInstance)`, e.g. `binder.setDefaultBindingConfigurator(AbstractTextField.class, bindingBuilder -> bindingBuilder.setNullRepresentation(""))`.

On the application level, it's of course also possible to define a simple subclass of `Binder` where the `createBinding` method (which is called internally from `forMemberField`) is overridden to do the customization so that the repetition could be moved out from individual field bindings.

**Closed** 2020-02-17 18:27 UTC
Labels: enhancement
