### ISSUE TITLE
Breaks ComboBox

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11059] opened 2018-07-16 15:03 UTC
Hi,

On Vaadin 8.4.1:

```
        VerticalLayout mainLayout = new VerticalLayout();

        ListDataProvider<String> dataProvider = new ListDataProvider<>(new ArrayList<>());

        Label label = new Label();
        mainLayout.addComponent(label);

        ComboBox<String> comboBox = new ComboBox<>("ComboBox");
        comboBox.setItems();
        comboBox.setDataProvider(dataProvider);
        comboBox.setNewItemProvider(value -> {
            dataProvider.getItems().add(value);
            dataProvider.refreshAll();

            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            return Optional.ofNullable(value);
        });
        mainLayout.addComponent(comboBox);

        Binder<AtomicReference<String>> binder = new Binder<>();
        binder.forField(comboBox)
                .asRequired("Required")
                .bind(AtomicReference::get, AtomicReference::set);

        Button button = new Button("Clear");
        mainLayout.addComponent(button);
        button.addClickListener(event1 -> {
            comboBox.setValue(null);
            dataProvider.getItems().clear();
            dataProvider.refreshAll();
        });
        solutionButtons.addComponent(mainLayout);

        Button button2 = new Button("Validate");
        mainLayout.addComponent(button2);
        button2.addClickListener(event1 -> binder.validate());
        solutionButtons.addComponent(mainLayout);
```

To reproduce the issue:
- Enter the value "myValue" in combobox field but don't press any key and don't click anywhere
- Click on the "Clear" Button
- Click on the "Validate" Button
- No way to choose the value "myValue" or to add another value and to validate for now

**Comment by anasmi** [comment] 2018-07-17 07:08
I think you are missing call `dataProvider.refresAll()`;  after you have added the new Item inside handler.
After this example seems to work for me.

**Comment by pinonpierre** [comment] 2018-07-17 09:17
Hi,

The "dataProvider.refreshAll()" is one forget of my minimal example code but in my project this instruction is present and I still have the issue.

I a little bit changed my example to still reproduce the issue.

I specially change this part of the code:

comboBox.setNewItemProvider(value -> { dataProvider.getItems().add(value); dataProvider.refreshAll();

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        return Optional.ofNullable(value);
    });

Thanks,

**Comment by anasmi** [comment] 2018-07-18 05:59
Was able to reproduce the problem using framework test. http://localhost:8888/run/ComboBoxNewItemProvider?restartApplication

This works, when user is clicking outside (value is send right away), but it doesn't when slow-downing the process + clicking resetButton (only blur action happens)

**Comment by tsuoanttila** [comment] 2018-07-19 12:54
With the current changes in `master` and `8.6-SNAPSHOT` the following happens:
1. The user inputs `myValue` and clicks Clear
2. User input `myValue` is still visible, but value of ComboBox is `null`
3. Click on Validate shows the `ComboBox` to be `Required`
4. Typing in `anotherValue` and clicking anywhere else than the Clear adds and selects the value.

To mention a small quirk in it, is the required warning is shown for a second until the client-side of the combobox tells the server to actually select the new value.

**Comment by tsuoanttila** [comment] 2018-07-25 10:35
@pinonpierre can you test if this work properly for you with the `8.6-SNAPSHOT` ?

**Comment by pinonpierre** [comment] 2018-07-25 12:53
Hi,

Nothing has changed from my side, it doesn't work in 8.6-SNAPSHOT
Have you tried my code below with the 8.6-SNAPSHOT?

**Comment by tsuoanttila** [comment] 2018-09-20 08:51
there's a WIP patch that works in the case of adding a new item with enter. There's a remaining bug that clicking/tabbing out to send the value it misbehaves and does not properly select the value. I am unable to continue with investigating the combobox internals for this case.

**Comment by ZheSun88** [comment] 2018-09-28 07:02
fixed with #11094

**Comment by ZheSun88** [comment] 2018-11-23 08:00
Reopen this issue : The commit has been reverted because it causes more problem in comboBox. This issue needs to be verified with current implementation.

**Comment by Legioth** [comment] 2018-11-23 08:36
Please don't reopen issue that have already been included in a released version. Otherwise, it will become difficult to track what was done in which version. I'd recommend opening a new issue instead.

**Comment by pinonpierre** [comment] 2018-11-23 08:44
And I need to know on which version your rollback will be effective.
Because I need to put my old workaround on all my project (return Optional.empty() on newItemHandler)

**Comment by ZheSun88** [comment] 2018-11-26 06:39
@Legioth Yes, i will close this one and verify the bug again. 

@pinonpierre The rollback will affect version after 8.6.2( will be released this week, according to schedule), But I noticed that `newItemHandler` has been marked with `deprecated`, please use `newItemProvider()` instead. On the other hand, Has this issue been fixed before? I have tested the reverted commit, but the bug is still there (when we do the new item adding and newItemProvider reset in the same roundtrip.) Could you help me to confirm that?

**Closed by ZheSun88** 2018-11-26 06:39 UTC
Labels: BFP

**Comment by pinonpierre** [comment] 2018-11-26 07:46
I already use "newItemProvider"

I don't know if the issue was present in 8.5.x because another bug prevented us to use this version.
I let you test it.
