### ISSUE TITLE
[Grid] Scroll position is not stored

### ISSUE THREAD

**Issue by glebfox** [vaadin/framework#10839] opened 2018-04-20 12:23 UTC
## Test Case

1. Scroll Grid to some position
2. Switch to another tab
3. Go back to the tab with Grid

**AR:**
Position moved to the top

**ER:**
Position persists

## Demo Project

```
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.UI;
import com.vaadin.ui.themes.ValoTheme;

import javax.servlet.annotation.WebServlet;
import java.util.ArrayList;
import java.util.List;

@Theme(ValoTheme.THEME_NAME)
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        TabSheet tabSheet = new TabSheet();
        tabSheet.setSizeFull();

        final Grid<Person> grid = new Grid<>();

        grid.addColumn(Person::getName).setCaption("Name");
        grid.addColumn(Person::getBirthYear).setCaption("Year of birth");

        List<Person> people = new ArrayList<>();
        for (int i = 0; i < 10000; i++) {
            people.add(new Person("Nicolaus Copernicus", 1473));
            people.add(new Person("Galileo Galilei", 1564));
            people.add(new Person("Johannes Kepler", 1571));
        }
        grid.setItems(people);

        tabSheet.addTab(grid, "First Tab");
        tabSheet.addTab(new Label("Second Tab"), "Second Tab");

        setContent(tabSheet);
    }

    private class Person {
        private String name;
        private int birthYear;

        public Person(String name, int birthYear) {
            this.name = name;
            this.birthYear = birthYear;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public int getBirthYear() {
            return birthYear;
        }

        public void setBirthYear(int birthYear) {
            this.birthYear = birthYear;
        }
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {

    }
}
```

## Test Environment

**Browser:** Google Chrome 66.0.3359.117
**Vaadin version:** `7.7.13` and `8.3.3`

**Comment by TatuLund** [comment] 2018-04-22 16:13
This happens on purpose. The TabSheet component will not retain the content of the Tabs in DOM to conserve resources.

There is handy add-on, that helps you with Grids and Tabs

https://vaadin.com/directory/component/gridscrollextension-add-on

**Comment by TatuLund** [comment] 2018-04-22 16:15
Duplicate of https://github.com/vaadin/framework/issues/6862

**Closed by TatuLund** 2018-04-22 16:15 UTC
Labels: enhancement, workaround
