### ISSUE TITLE
Grid tabbing issues

### ISSUE THREAD

**Issue by aoede3** [vaadin/framework#8847] opened 2017-03-15 09:41 UTC
Vaadin version: 7.7.7

Whilst using the Grid there are some issues with tabbing.

Attached are two videos to show issues from:
[curo.gz](https://github.com/vaadin/framework/files/843978/curo.gz) [this is a .zip rename .gz to upload?!]
http://demo.vaadin.com/sampler/#ui/grid/multi-select
https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/columns.html#toc_3_frozen_columns

For instance, whilst tabbing through elements such as checkboxes (or any other
tabbable element in a Grid) the Grid does not update its scrollbar with the new
focused position nor does it scroll the Grid to redraw.

In addition, instances of the Grid with frozen columns whilst tabbing through
elements you will note the frozen columns disappear when tabbing beyond the
currently viewable area displayed. They reappear on physically moving the Grid
scrollbar.

**Comment by simon-chromow** [comment] 2017-12-13 15:41
Reproducible in 8.1.7

**Comment by TatuLund** [comment] 2018-05-05 20:24
I think this is duplicate of https://github.com/vaadin/framework/issues/8188 and fixed in 8.4.0

**Comment by TatuLund** [comment] 2018-10-03 06:19
Closed as duplicate, fixed in 8.40

**Closed by TatuLund** 2018-10-03 06:19 UTC
Labels: duplicate
