### ISSUE TITLE
DateTimeField with resolution DAY should replace time with zeros

### ISSUE THREAD

**Issue by krizda** [vaadin/framework#11069] opened 2018-07-18 11:43 UTC
Version 8.4.3
DateTimeField with resolutin day sets DateTime if set programmicaly.
If I have two datetimefields with start and end date, than if start date is automatically current time and end date is the same day, than start date is after end date.

```
public class MyUI extends UI {
    DateTimeField dateTimeField = new DateTimeField();
    Binder<DateBean> binder = new Binder<>();
    DateBean dateBean = new DateBean();
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        layout.addComponent(dateTimeField);
        dateTimeField.setResolution(DateTimeResolution.DAY);
        dateBean.setLocalDateTime(LocalDateTime.now());
        binder.setBean(dateBean);
        binder.bind(dateTimeField, DateBean::getLocalDateTime, DateBean::setLocalDateTime);
        layout.addComponent(new Button("", clickEvent -> {
            binder.validate();
            layout.addComponent(new Label(binder.getBean().getLocalDateTime().toString()));
        }));
        setContent(layout);
    }

    class DateBean{
        LocalDateTime localDateTime;

        public LocalDateTime getLocalDateTime() {
            return localDateTime;
        }

        public void setLocalDateTime(LocalDateTime localDateTime) {
            this.localDateTime = localDateTime;
        }
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

}

```
Simple example.

If you click the button after init, than it will have time. After changing it will have only date(As expected).

**Comment by scardanzan** [comment] 2020-05-06 19:40
Tested sample code with Vaadin 8.10.3 and after init and after selecting a date the date has no time. Its working properly.

**Comment by TatuLund** [comment] 2020-05-08 13:17
Closing as cannot reproduce, it may have been broken in earlier versions and fixed by one of the numerous patches to DateField.

**Closed by TatuLund** 2020-05-08 13:17 UTC
Labels: cannot reproduce
