### ISSUE TITLE
Clear ComboBox filterText after adding a new item with NewItemHandler

### ISSUE THREAD

**Issue by tistvan** [vaadin/framework#9640] opened 2017-07-05 09:40 UTC
Hello,

When I add a new item to a ComboBox using a NewItemHandler and I don't want to select the new item the filter text remains in the combobox. I think there shuld be a setFilterText() or at least a clearFilterText() method in ComboBox.
(The reason I don't want to select the new item is I am creating a UI in which when the user selects an item from a ComboBox it is added to a grid.)

Thanks

**Comment by TatuLund** [comment] 2018-04-06 04:41
This is likely to be duplicate of https://github.com/vaadin/framework/issues/10284 

Have you checked 8.3.1, which has this fix: https://github.com/vaadin/framework/issues/10284 ? There will be further improvement in 8.4.0 via https://github.com/vaadin/framework/pull/10606

**Closed by TatuLund** 2018-04-06 04:41 UTC
Labels: duplicate
