### ISSUE TITLE
Interface.FieldEvents.FocusListener not working on some browsers

### ISSUE THREAD

**Issue by JokerTheFourth** [vaadin/framework#10414] opened 2017-12-05 14:34 UTC
Vaadin versions: 8.1.7, 8.1.6, 8.1.5, 8.1.4
A call of FocusListener (**interface.FieldEvnets.FocusListener**) not working on some browsers like Microsoft Edge or Firefox but it works well with Google Chrome and Opera.

Example:
`textField.addFocusListener(new FocusListener() {
     @Override
     public void focus(FocusEvent event) {
         Notification.show("It works!");
     }
 });`

**Comment by wbadam** [comment] 2017-12-29 14:25
Hi, I couldn't reproduce the issue using 8.1.4 on FF 56, IE11 or Edge with the given simple app that only contains the text field. All browsers seems to show the notification when the text field is focused.
Do you have some additional setup that could interfere with the event handling? Did you try the feature just with a very simple app?

**Comment by JokerTheFourth** [comment] 2018-01-04 13:12
Hi Adam,

I tried feature with simple app as you mentioned and it worked. But the
problem occurs in a more complex project structure.

For example: In my company, we took your Bakery starter App (Jave EE) and
adapted it to our requirements, but here FocusListener event doesn't work
on some browsers (Edge, Firefox).

For better understanding I attached .zip file. Here you'll find two maven
projects:

   - focus_example_1 - simple app where everything works fine
   - focus_example_2 - project where FocusListener doesn't work on Edge and
   Firefox browser.

I also tried FocusListener on Bakery App project where issue also occurs.

Vaadin version: 8.2.0

Best regards and of course Happy 2018!

Leon Stanko

2017-12-29 15:26 GMT+01:00 Adam Wagner <notifications@github.com>:

**Comment by draganr** [comment] 2018-04-13 14:11
I have the same problem with BlurListener in TextField inside complex project structure with Firefox Browser. Issue is: #10805

**Comment by TatuLund** [comment] 2018-04-13 18:14
I tested Focus and Blur listeners on Windows 10 / Edge (41.16299.371.0), Vaadin 8.3.1 and they both triggered correctly. There is number of reports of this issue, which indicates that something has gone wrong somewhere, but so far we have been unable to reproduce the issue.

**Comment by mcollovati** [comment] 2018-04-13 21:32
I don't know why but in the attached project (`focus_example_2`) the problem seems related to `vaadin-board-precompiled` dependency and more specifically to the `webcomponents-lite.js` script.

If you remove from pom the dependency to `vaadin-board-precompiled` the focus listener works.

It work also with `vaadin-board-precompiled` if you prevent `webcomponents-lite.js` to be loaded (eg with a Filter that intercepts the call and returns an empty response)

**Comment by TatuLund** [comment] 2018-04-14 06:52
@mcollovati Excellent observation!

webcomponents-lite.js is the polyfill library used with Board, since it is a webcomponent (we use webcomponents polyfill also in Flow). It quick glance I did not find generic issue reported in their issue tracker

https://github.com/webcomponents/webcomponentsjs/issues

If this turns out to be bug in polyfills library (i.e. it is somehow blocking the event), the issue should be filed there.

Similar issue has not been reported with Flow either yet.

**Comment by Artur-** [comment] 2018-04-15 12:14
Board precompiled probably contains a quite old version of the polyfill. Would make sense to upgrade to the latest to see if it resolves the issue

**Comment by draganr** [comment] 2018-09-13 12:48
I have checked with Vaadin 8.6.0.alpha1 ana Firefox 62.0 and the bug is still active as long as I have a Board add on within my project.

**Comment by devdev-dev** [comment] 2018-10-01 12:41
We too have the problem with ignored focus and blur events. We do not have a problem with the newest Firefox but with Edge and the Internet Explorer. We tried the deprecated Vaadin 7 and Vaadin 8 TextField component. For both versions, we are not receiving any focus or blur event.  

We tested the following browsers/versions:
- **Works** Firefox 63
- **Does not work** Edge 42.17134.1.0 
- **Does not work** IE 11.285.17134.0

**Comment by draganr** [comment] 2018-10-01 12:55
Do you use Vaadin Board add on in your project?

**Comment by devdev-dev** [comment] 2018-10-01 13:13
> @devdev-dev Do you use Vaadin Board add on in your project?

Nope - We are not using the Vaadin Board Add On.

**Comment by devdev-dev** [comment] 2019-09-30 08:55
Unfortunately, the problem is still relevant and does not allow the use of Edge Browsers. 
Is there any known fix or an updated version without that problem?

Works Chrome 77.0.3865.93
Works Firefox 69.0.1
Does not work Microsoft Edge 44.18362.329.0

We are using Vaadin 8.7.0

**Comment by TatuLund** [comment] 2019-10-19 11:34
I think this should have been fixed by https://github.com/vaadin/board/issues/144

**Closed** 2019-10-19 11:34 UTC
