### ISSUE TITLE
DownloadStream getContentDispositionFilename wrongly performs URL encoding on filenames

### ISSUE THREAD

**Issue by roeltje25** [vaadin/framework#8230] opened 2017-01-12 09:49 UTC
In the DownloadStream class getContentDispositionFilename generates a URL encoded filename and encloses it between quotes. When I use e.g. a filename with spaces this results in the final download save as window to include + signs in the file name. This is of course not wanted. Instead the encoding should follow the RFCs 2183 and 2184. In short it's a bit more cumbersome, but at least when between double quotes, it should not be URL encoded.

related class is com.vaadin.server.DownloadStream line 331 for Vaadin version 7.7.6

EDIT: it apparently should be URL encoded for firefox. but not completely it should be a pure percent encoding so the proposed revision should be on line 333
`String encodedFilename = URLEncoder.encode(filename, "UTF-8").replace("+", "%20");`

**Comment by Legioth** [comment] 2017-01-12 11:09
I believe this was fixed by #6607 which will be included in the next maintenance release we do.

**Comment by Legioth** [comment] 2017-01-23 07:45
I'll just close this based on the assumption that it's a duplicate of #6607. Please reopen if it turns out that this is not the case.

**Closed by Legioth** 2017-01-23 07:45 UTC
