### ISSUE TITLE
DataProvider.refreshItem(item) seems to not work with Grid

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9470] opened 2017-06-01 10:57 UTC
In Vaadin 8.0.5,

As I know that only one item has changed in my DataProvider, I tried to call DataProvider.refreshItem(item) of my provider to provoke the refresh but nothing change. (FYI: I defined "Object getId(T item)" in the DataProvider)

It works has expected when I used DataProvider.refreshAll()

Thanks,

**Comment by Artur-** [comment] 2017-06-01 11:38
Probably fixed in 8.1 by #9380

**Comment by tsuoanttila** [comment] 2017-06-05 08:47
@pinonpierre can you test the 8.1.0.beta1 or 8.1-SNAPSHOT and verify if this is still an issue for you?

**Comment by pinonpierre** [comment] 2017-06-07 16:08
Yes, I tried in Beta1 and I still have this issue

**Comment by tsuoanttila** [comment] 2017-06-08 08:23
Can you post a minimal code example to reproduce your issue? With the description alone debugging the possible issue is quite impossible.

**Comment by pinonpierre** [comment] 2017-06-08 10:06
It was very difficult to reproduce this bug in a minimal code.

In fact, I have a second bug in 8.1.0.beta1 because my workaround was to use "dataProvider.refreshAll();" instead of "dataProvider.refreshItem(myObject);" but in 8.1.0.beta1, it produces an exception:

 ```
Duplicate key com.sma.sm.core.ui.view.HomeView$MyObject@597903d
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.data.provider.DataCommunicator$ActiveDataHandler.getActiveData(DataCommunicator.java:165)
	at com.vaadin.data.provider.DataCommunicator.refresh(DataCommunicator.java:506)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.ui.components.grid.MultiSelectionModelImpl.lambda$updateSelection$3(MultiSelectionModelImpl.java:456)
	at com.vaadin.ui.components.grid.MultiSelectionModelImpl.doUpdateSelection(MultiSelectionModelImpl.java:468)
	at com.vaadin.ui.components.grid.MultiSelectionModelImpl.updateSelection(MultiSelectionModelImpl.java:447)
	at com.vaadin.ui.components.grid.MultiSelectionModelImpl$GridMultiSelectServerRpcImpl.select(MultiSelectionModelImpl.java:65)
	... 48 common frames omitted
```

To reproduce exception of this second bug:
- Comment on my code "dataProvider.refreshItem(myObject);"
- Uncomment on my code "dataProvider.refreshAll();"
- Click on the button
- Select by the checkbox the item that just changed

All theses problems occurs when a DataProvider.getId is defined because equals result of the item changed!

The code,
First, the item class:
```
public static class MyObject {

        private final int id;
        private String name;

        public MyObject(int id, String name) {
            this.id = id;
            this.name = name;
        }

        public int getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o)
                return true;
            if (o == null || getClass() != o.getClass())
                return false;

            MyObject myObject = (MyObject) o;

            if (id != myObject.id)
                return false;
            return name != null ? name.equals(myObject.name) : myObject.name == null;
        }

        @Override
        public int hashCode() {
            int result = id;
            result = 31 * result + (name != null ? name.hashCode() : 0);
            return result;
        }
    }
```

Now, the code:

  ```
        List<MyObject> data = new ArrayList<>();
        data.add(new MyObject(0, "blue"));
        data.add(new MyObject(1, "red"));
        data.add(new MyObject(2, "green"));
        data.add(new MyObject(3, "yellow"));
        data.add(new MyObject(4, "purple"));

        ListDataProvider<MyObject> dataProvider = new ListDataProvider<MyObject>(data){

            @Override
            public Object getId(MyObject item) {
                return item.getId();
            }
        };

        Grid<MyObject> grid = new Grid<>();
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.setDataProvider(dataProvider);
        mainLayout.addComponent(grid);

        grid.addColumn(myObject -> myObject.getName());

        Button button = new Button("Do it!");
        button.addClickListener(event1 -> {
            MyObject myObject = data.get(2);
            myObject.setName("black");
            dataProvider.refreshItem(myObject);
//            dataProvider.refreshAll();
        });
        mainLayout.addComponent(button);
```

To resume, in 8.1.0.beta1, I have no way to update the item.

Thanks,

**Comment by tsuoanttila** [comment] 2017-06-08 10:28
At least the first issue I found when testing this is the fact that your items hashCode depends on the field that you modify. And because of how java.util.HashMap works, it seems to lose sight of the object after name change and generates a new key for it. Full reset works because it considers everything a new object. The individual update re-uses the same key to inform the client-side that this particular item is updated, but since the key is new, client-side does not recognise the updated object.

**Comment by tsuoanttila** [comment] 2017-06-08 10:54
After looking a bit deeper into this, it seems there is still some kind of a lingering problem in this issue. Made a minimal patch, will include your test code as is.

**Closed** 2017-06-21 08:14 UTC
