### ISSUE TITLE
Tree paint problem if tree is component of a vertical split panel

### ISSUE THREAD

**Issue by karstenlehmann** [vaadin/framework#11102] opened 2018-08-06 08:18 UTC
I got a paint problem with my tree component. I have the following UI structure. The tree and a label are contents of a Verticallayout (V1). V1 the upper content of a vertical split panel. If i play with the split position and the tree (fold / unfold) sometimes i got a paint error (see attachment). The tree displays multiple entries in one row. 

- Vaadin Framework version (e.g. 8.5.0)
- Browser version: Internatl eclipse browser, Chrome + IE

Attachments:
Paint Error 
![tree paint problem](https://user-images.githubusercontent.com/42135618/43704724-df7c23e2-9960-11e8-8b54-24040bd5805a.PNG)

Application to reproduce the error

```
@Theme("mytheme")
public class MyUI
    extends UI {

  @Override
  protected void init(VaadinRequest vaadinRequest) {
    Tree<String> tree = new Tree<>();
    tree.setSizeFull();

    // An initial planet tree
    TreeData<String> treeData = new TreeData<>();

    // Couple of childless root items
    treeData.addItem(null, "Mercury");
    treeData.addItem(null, "Venus");

    // Items with hierarchy
    treeData.addItem(null, "Earth");
    treeData.addItems("Earth", "The Moon", "X", "Y", "Z");
    treeData.addItems("Venus", "1", "2", "3", "4");
    treeData.addItems("X", "X1", "X2", "X3", "X4");
    treeData.addItems("Y", "Y1", "Y2", "Y3", "Y4");
    tree.setTreeData(treeData);

    VerticalLayout vl = new VerticalLayout(tree, new Label("Test 123"));
    vl.setSizeFull();
    vl.setMargin(false);
    vl.setSpacing(true);

    VerticalSplitPanel vsp = new VerticalSplitPanel(vl, new Label("Second component"));
    vsp.setSizeFull();

    setContent(vsp);
  }
}
```

**Comment by TatuLund** [comment] 2019-11-11 13:22
I can't reproduce this issue with Vaadin 8.9.2 anymore. The problem has been probably fixed via the Escalator patch we had in Vaadin 8.9.0.

**Closed by TatuLund** 2019-11-11 13:22 UTC
Labels: cannot reproduce
