### ISSUE TITLE
Placeholders in TextFields are not being updated properly

### ISSUE THREAD

**Issue by skilawalker** [vaadin/framework#11498] opened 2019-03-15 11:38 UTC
Once a placeholder is set in a TextField, it cannot be changed anymore. You can call the setPlaceholder with the new text and no error is reported, but the text is no changed. 
This issue is specially critical on locale changes, where all the text pieces should be updated according to the new selected locale. 
Notice that this issue only applies to version 13.0.x. In Vaadin 12.0.7, TextFields works properly.

**Comment by TatuLund** [comment] 2019-03-15 12:20
This issue should be reported in other issue tracker. Either https://github.com/vaadin/vaadin-text-field or https://github.com/vaadin/vaadin-text-field-flow. I checked if the issue is reported there already, and found this:

https://github.com/vaadin/vaadin-text-field/issues/323

Is this the same issue?

**Comment by TatuLund** [comment] 2019-03-20 06:46
This issue has been fixed in Vaadin 13.0.1

**Closed by TatuLund** 2019-03-20 06:46 UTC
Labels: duplicate, invalid
