### ISSUE TITLE
Paged TreeGrid

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#12125] opened 2020-10-19 08:13 UTC
The TreeGrid doesn't fetch the topmost items in a paged manner - it tries to fetch them all at once. This unfortunately doesn't work well with the scenario where there's a 100k+ worth of topmost items.

I understand it can be very difficult to fix TreeGrid itself; I'm opening the bug report partly to start a conversation about a possible fix, partly to learn about a possible workaround.

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version: 8.11.3
- Browser version: Firefox 81.0.2
- Web container name and version: Tomcat 9.0.31

Related to forum topic: https://vaadin.com/forum/thread/18077691/paging-the-data-in-the-treegrid

**Comment by mvysny** [comment] 2020-10-19 08:16
Attaching an example app which reproduces the issue. Simply run the app in Tomcat via `./gradlew appRun` and open http://localhost:8080. The app logs data fetches and will print lots of `FETCHING 0/100001` indicating that the TreeGrid fetches all items from the offset 0 and limit 100001.

[karibu-helloworld-application.zip](https://github.com/vaadin/framework/files/5400176/karibu-helloworld-application.zip)

**Comment by TatuLund** [comment] 2020-10-19 08:28
I think this is somewhat duplicate of this earlier report https://github.com/vaadin/framework/issues/11447

**Closed** 2020-10-19 08:44 UTC
Labels: duplicate
