### ISSUE TITLE
Vaadin 8.1.0.rc1 Tree ScrollBar doesn't work correctly and appareance is not correct

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9644] opened 2017-07-06 09:10 UTC
On Vaadin 8.1.0.rc1

I have a tree with only 3 items.
When I expand items, scroll bar should appear (Vertically and Horizontally) to allow to scroll but nothing happen.

**Comment by elmot** [comment] 2017-07-06 13:48
Related to #9503, #9629

**Comment by wbadam** [comment] 2017-08-31 10:21
Duplicate of #9628? I think it's fixed now.

**Comment by pinonpierre** [comment] 2017-08-31 10:34
The scrollBars works but the style of scrollbars is bad

![image](https://user-images.githubusercontent.com/4507910/28783309-42a6382e-7610-11e7-9335-aa195ad94476.png)

**Closed** 2017-09-04 11:59 UTC
