### ISSUE TITLE
Grid editor column not resizing 

### ISSUE THREAD

**Issue by scrmtrey91** [vaadin/framework#12035] opened 2020-06-17 07:37 UTC
Vadin 8.11.0 (it is not version dependent)

When grid editor is opened and user change column width by mouse grid editor column does not resize with original grid column width.

**Comment by TatuLund** [comment] 2020-06-17 07:58
This is duplicate of https://github.com/vaadin/framework/issues/7276

There is fix available as Grid extension in the Directory

https://vaadin.com/directory/component/grideditorcolumnfix-add-on

(There are actually handful of bug cases in Editor column sizes fixed by the add-on)

**Closed by TatuLund** 2020-06-17 07:58 UTC
Labels: duplicate
