### ISSUE TITLE
Internet Explorer 11, UI freezes on some resize events

### ISSUE THREAD

**Issue by drewoko** [vaadin/framework#10769] opened 2018-03-28 10:20 UTC
Vaadin 8.3.0. Vaadin UI freezes when making some resize event's in Internet Explorer 11. It easilly can be reproduced by openning and closing with F12 .

Steps: 
1) Download demo project [issue.zip](https://github.com/vaadin/framework/files/1855510/issue.zip)
2) Open in IE11 
3) Hit F12 for openning developer console 
4) Hit F12 once again for closing console 
5) Try to click on "Click!" button.

Result: Vaadin UI freezes, feels like in permament loading state.

Expected result (correct): Notification should be shown, works with "normal" browsers.

**Comment by drewoko** [comment] 2018-05-07 07:57
Issue prioritized in Vaadin Prime.

**Comment by tsuoanttila** [comment] 2018-07-10 07:13
After testing this numerous times with different UIs and different setups, I did find out that _something_ happens in the IE JavaScript engine. Unfortunately the crash provides no stacktrace of any kind and seems to hang the entire Vaadin widgetset execution, possibly due to restarting the JavaScript engine completely. The response from the server is never processed and the page is left in an unresponsive state. 

This seems to be related to the `Timer`? based communication of browser size changes from client to server, but even without the `Timer` it can still fail. It *might* provide some help to IE11 users to increase the server update delay to make sure IE is done with the resize before sending the request to the server, but it will not prevent the issue from happening.

**Comment by Artur-** [comment] 2018-07-11 06:11
This can be reproduced without a grid and with a UI containing only a VerticalLayout. Using ?debug you can see that events are sent to the server when the browser is resized.

I do not see how this is related to resize events though as it reproduces if you open dev tools in a separate window also. After closing it, no more events are sent to the server and no more resizes are even detected in the browser. Seems more like a IE11 bug which causes all JS to stop working when dev tools are closed. This in turn sounds very strange because somebody should have noted it a long time ago.

Note also that if you open dev tools in the same window and then close dev tools quickly, the request handling seems frozen, just like JS execution was stopped. The loading indicator wil be shown forever. If you wait for the request to finish before closing dev tools, then there is just no events anymore.

I quickly tried with 8.0.0 also but the results were quite inconclusive as the problem seems to manifest a bit randomly

**Closed** 2018-07-19 06:55 UTC
Labels: BFP, bug, wontfix

**Comment by mvysny** [comment] 2019-05-06 12:43
> Got a negative max width for a column, which should be impossible.

That one is easily reproducible: https://github.com/vaadin/framework/issues/11557
