### ISSUE TITLE
Empty rows in table after scrolling

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#7964] opened 2016-12-13 10:55 UTC
This is a resurfacing of an old issue https://dev.vaadin.com/ticket/6160, which I can't seem to find from GitHub. 

The issue from the original ticket:"
When scrolling up and down (right scrollbar) in a table and pagination is activated, the table is not always rendered correctly.
The table contains empty rows.
After refresh or scrolling up again the table is renderded correct again (empty rows disapeared).
"

The original issue was reported for Vaadin 6, but I was able to reproduce it with 7.7.6 with the latest Chrome on Windows 10. 

The test scenario in the attached project contains an artificial Thread.sleep() in a generated column's generateCell methods, which simulates loading data from a backend service. The table's pageLength is set to 25 and cacheRate is 1.

Reproducing the issue not completely reliable, but I can usually cause it in less than a minute of scrolling up and down.

Attached maven test project:
[scroll-bug-test.zip](https://github.com/vaadin/framework/files/648643/scroll-bug-test.zip)

**Comment by marianavarroit** [comment] 2017-03-28 09:46
The same for me. I reproduced the same issue with lazy queries (for huge amount of date) using Table and BeanItemContainer. Sometimes when scrolling, some cells dissapear: The problem is with generated columns. Columns without generators are shown perfectly!

**Comment by bednar** [comment] 2017-06-07 08:05
Same issue affect our application with Vaadin 7.7.6. Is there any progress for fix this issue @tsuoanttila ?

**Comment by mlindfors** [comment] 2017-06-08 13:49
I'm here to keep this particular issue alive as well. A client has a product and their users are hitting this same issue quite often. I did a rather ugly workaround, but a real fix in framework would be preferred. And yes, this is still happening in Vaadin 7.7.9.

Anyway, as far as I can tell, the descriptions in #5030 are quite accurate in describing the root cause. At least I came to similar conclusions separately before actually even finding that ticket. The methods for working around it aren't quite right, though. As far as I can tell, cacheRate has very little effect on the matter.

Things indeed do break in the method removeUnnecessaryRows inside Table's server side class. To me it looks like there's something off in calculating the amount of rows to be removed, if the rows are to be removed from the beginning of the buffer. In certain cases the thing removes all the rows, I got this to happen when pageBufferFirstIndex was 0 and minPageBufferIndex was something above 0. I suppose if the amount of rows to remove was currentlyCachedRowCount - maxBufferSize, it would be a bit more sane. Unless TreeTable uses those in a totally different manner, in which case it would break, again.

Then again I have this nagging feeling that at least in Table's case, the buffer that particular method is removing rows from is the already refreshed row cache and the rows and the components on them are already visible and attached to the DOM. Thus removing them leads to missing components.

As a first-aid measure, I just kludged the call to removeUnnecessaryRows to happen only if we're in a TreeTable instance. This probably isn't a viable fix in the long run. I'll investigate this a bit further still.

**Comment by mlindfors** [comment] 2017-06-16 11:48
After rather considerable amount of testing and poking around, I've come to the conclusion that the whole removeUnnecessaryRows method is pretty much vestigial. It doesn't seem to have a meaningful purpose anymore, as it just causes problems whenever it actually does something. Luckily most of the time it just exits without touching anything. And it also breaks things in a TreeTable, so as far as I can tell, it could and should just be removed. It might have provided a useful function 5-6 years ago, but other changes around it have made it obsolete.

**Comment by hesara** [comment] 2017-08-09 11:28
Addressed in 7.7.11 (#9551) and 8.1.2 (#9800)

**Closed** 2017-08-09 11:28 UTC
