### ISSUE TITLE
Screen drawn error.

### ISSUE THREAD

**Issue by querryjk** [vaadin/framework#10808] opened 2018-04-11 07:10 UTC
Since I upgraded to Vaadin 8 (I currently have vaadin 8.1.4), I have an error in the redraw of the screen, when I update a value from a ValueChangeListener and the visual component it is in a HorizontalLayout. This happens with any browser. Attached 2 images so you can see what happens when I change the TextField value b.
**This only happens if the Textfield b has no caption or i have more component in HorizontalLayout  without caption,  and one component in horizontal layout is expanded**
A greeting.

![imagen1](https://user-images.githubusercontent.com/32563663/38601038-9991d576-3d66-11e8-8ea4-5220f22ae793.JPG)

![imagen2](https://user-images.githubusercontent.com/32563663/38600911-20b2abb2-3d66-11e8-8f1f-e86b48f00e6f.JPG)

Source code:

		VerticalLayout vLayout= new VerticalLayout();
		HorizontalLayout hLayout= new HorizontalLayout();
		hLayout.setWidth("100%");

		TextField a= new TextField();
		a.setWidth("100%");

		TextField b= new TextField();// important textfield without caption

		vLayout.addComponent(hLayout);
		hLayout.addComponents(a,b);

		hLayout.setExpandRatio(a, 1f);// important layout with expandRatio

		b.setValueChangeMode(ValueChangeMode.BLUR);
		b.addValueChangeListener(e->{
			b.setValue(e.getValue().toUpperCase());
		});		
		setContent(vLayout);

**Comment by TatuLund** [comment] 2019-11-16 18:20
Closed as duplicate of https://github.com/vaadin/framework/issues/10734

**Closed by TatuLund** 2019-11-16 18:20 UTC
Labels: duplicate
