### ISSUE TITLE
Binder.setReadOnly(true) & binder.writeBean(...)

### ISSUE THREAD

**Issue by timothyneill** [vaadin/framework#11134] opened 2018-08-22 22:53 UTC
I discovered this when trying to upgrade to Vaadin 8.4.0 but I couldn't find the bug (until today).

I'm attaching the code for an abstract form which has Save, Cancel & Reset buttons. The function call you are looking for starts at line 212. 

I am basically reading and writing from a bean without setting it to the binder. The problem is when I set the binder to read only, only null values are assigned to the bean when I use the writeBean(...) command. 

I googled for a duplicate issue but could not find it. Please let me know if you need additional files / information.

Thanks so much, 

Timothy
timothy.c.neill@gmail.com

[abstractForm.java.zip](https://github.com/vaadin/framework/files/2312219/abstractForm.java.zip)

**Comment by anasmi** [comment] 2019-04-08 12:17
As @AndreiBoaghe noticed, the decision behind this breaking change is described here in details : https://github.com/vaadin/framework/issues/10897#issuecomment-387329225 
I will close this ticket due to this,as this is an intended behavior. As suggested in the ticket, you could set read-only to each field, instead of setting it to the binder.

Please, create a new ticket with the improvement ideas or comment here, if you think that something could be done different. 

Thank you for your contribution and investigation in this ticket ! :)

**Closed by anasmi** 2019-04-08 12:17 UTC
