### ISSUE TITLE
Timing problem with MenuItem in vaadin7

### ISSUE THREAD

**Issue by cdir** [vaadin/framework#11308] opened 2018-11-13 10:22 UTC
Some MenuItems does not propagate the click event to server when I just have changed any text field. In this cases the value-change is propagated but the click not.

By setting a breakpoint in VaadinService#handleRequest the problem is not reproduceable. With my laptop I could only reproduce the bug when AC is plugged but not in battery state :)
That means the timing problem seems to depend on the cpu performance.

It is not reproducable with a simple one-field-application. Also not reproduceable with every MenuItem.

**Comment by cdir** [comment] 2018-11-21 09:59
I can reproduce the bug now in a simple setup. The trick is: our data binding frameworks updates all component errors when any field changes. That means: if you have a text field and a menu item, just add a blur listener to the textfield and call setComponentError(null) at the menubar. Now when you type some text in the text field and directly click the menu item, the click is not propagated. It is still a timing problem that is not always reproducable.

**Comment by OlliTietavainenVaadin** [comment] 2018-11-23 14:49
Closing as a duplicate of #11333 .

**Closed by OlliTietavainenVaadin** 2018-11-23 14:49 UTC
Labels: BFP, v7
