### ISSUE TITLE
ComboBox.newItemProvider Issue when an new Item is set a second time /2

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11347] opened 2018-11-30 15:29 UTC
Hi,

I still have the bug in 8.6.2

https://github.com/vaadin/framework/issues/11317

Regards,

**Comment by pinonpierre** [comment] 2018-12-12 15:52
Still in 8.6.3

**Comment by anasmi** [comment] 2018-12-13 06:03
I am not able to reproduce this bug anymore in 8.6.3 following the steps described in the ticket above.

I will close this issue due to this, but , please, create a new one, with the steps how to reproduce, description and code snippet, if the problem still exists for you under any circumstances.

**Closed by anasmi** 2018-12-13 06:03 UTC

**Comment by pinonpierre** [comment] 2018-12-13 09:45
For Information: dataProvider.refreshAll() must be used instead of dataProvider.refreshItem(value) to see the fix work.
