### ISSUE TITLE
Bug: NativeSelect not changing properly HTML/CSS disabled property with setEnabled()

### ISSUE THREAD

**Issue by SevenEvos** [vaadin/framework#10602] opened 2018-02-05 12:36 UTC
Vaadin Framework version 8.3.0 (from pom.xml) using Eclipse Oxygen 2 Java EE.

Let's assume a Layout that has 4 row and 3 columns of NativeSelect<String> (3x4 matrix). NativeSelect have empty item ON. Only 1 NativeSelect per row can have a selected item, others will be disabled until selected item is deleted by selecting empty item. When user selects a value of a NativeSelect, ChangeValueListener() updates all other NativeSelect item list (it creates a new array of items, and it lefts out the item that user selected/triggered ChangeValueListener()). ChangeValueListener() also disables other NativeSelect that are on the same row. All NativeSelect use setResponsive(true).

Problem is, when I test this manually in Chrome, the setEnabled() just changes the NativeSelect component CSS class (you can still click and select items, but it has been greyed out). Chrome inspector shows: v-disabled CSS applied, but in <select> tag, parameter disabled="" is not present (disabled="" disables the tag).

Then more strange, when I load stored values programmatically using setSelectedItem() (in the same order as when clicking manually), CSS class v-disabled is applied and also <select> parameter disabled="" is applied, but the problem now is that when I select the empty item on the enabled NativeSelect to reEnable other NativeSelects on the same row, they lose v-disabled CSS class but the HTML disabled="" parameter remains applied... it is all really strange behavior and I really think setSelectedItem() does not the same as clicking component by mouse.

I tried the same with TextField instead of NativeSelect<String>. It works ok with them.
Also tried using NativeSelect getDataProvider.refreshAll(), it works but only every 2 clicks on NativeSelects :O

It is difficult to reproduce problem, but I think problem lies on Vaadin refreshing NativeSelect  component CSS and HTML tag parameters. In Vaadin 7 there was no problem with this code (NativeSelects work very different) when using setImmediate(true) method. With Vaadin 8 if I understand this is set true always.

For the moment I am forced to continue project in Vaadin 7, any help will be really appreciated!

**Comment by martin-garnier** [comment] 2018-02-09 00:36
I reproduce the same problem with version 8.1.7. Can't find any workaround for this.

**Comment by martin-garnier** [comment] 2018-02-09 14:58
Duplicate of https://github.com/vaadin/framework/issues/9956, actually.

**Comment by SevenEvos** [comment] 2018-02-14 11:32
Thank you for pointing that out. I think setEnabled is an important feature of HTML NativeSelect, hope it gets fixed.

**Comment by elmot** [comment] 2018-03-14 09:45
Fixed by #10710

**Closed by elmot** 2018-03-14 09:45 UTC
