### ISSUE TITLE
v8.1.0.beta1 ColorPickerGrid  ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by rgunn** [vaadin/framework#9474] opened 2017-06-04 04:09 UTC
8.1.0.beta1

```
// reproduced as a field on layout
new ColorPickerGrid(createAllColors(14,10));
```
```
// reproduced using default Vaadin popup
cp = new ColorPicker();
cp.setSizeFull(); 
cp.setCaption("Header Background Color");
cp.setRGBVisibility(true);
cp.setSwatchesVisibility(true);
cp.setHSVVisibility(true);
cp.setValue(new Color(158, 195, 45));
```

SEVERE: 
java.lang.ArrayIndexOutOfBoundsException: 10
	at com.vaadin.ui.components.colorpicker.ColorPickerGrid$1.select(ColorPickerGrid.java:41)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:145)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:235)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:520)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)

<img width="735" alt="screen shot 2017-06-04 at 2 54 27 pm" src="https://cloud.githubusercontent.com/assets/4567115/26759067/e6534906-4935-11e7-9158-070dcd6dce7e.png">

**Comment by krasnyt** [comment] 2017-06-05 08:04
Same as #9018 and still waiting for fix.

**Comment by hesara** [comment] 2017-06-21 11:36
Closing as duplicate of #9018.

**Closed by hesara** 2017-06-21 11:36 UTC
