### ISSUE TITLE
DateField does not fire the blur event. 

### ISSUE THREAD

**Issue by Olafxso** [vaadin/framework#11082] opened 2018-07-24 12:10 UTC
DateField does not fire the blur event. 
Tested with Vaadin 8.4.5  on Windows 10 (edge, chrome and firefox)
Also on Android (samsung browser and chrome).

Here a litle example. The TextField does fire the blur event, the DateField not.
```java
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.Title;
import com.vaadin.event.FieldEvents.BlurEvent;
import com.vaadin.event.FieldEvents.BlurListener;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

@SuppressWarnings( "serial" )
@Title( "Test" )
@Theme( "valo" )
public class MyUI extends UI
{
  @Override
  protected void init( VaadinRequest request )
  {
    BlurListener blurListener = new BlurListener()
    {
      @Override
      public void blur( BlurEvent event )
      {
        Notification.show( event.toString() );
      }
    };

    TextField txt = new TextField( "TextField (blur event ok)" );
    txt.addBlurListener( blurListener );

    DateField dt = new DateField( "DateField (no blur event)" );
    dt.addBlurListener( blurListener );

    setContent( new FormLayout( txt, dt ) );
  }
}
```

**Comment by edler-san** [comment] 2018-12-11 09:12
Other affected versions: 8.3.1, 8.5.1, 8.6.2.
Last version I found was 8.2.1

**Comment by ZheSun88** [comment] 2019-01-03 13:46
I think this issue is quite related to this commit https://github.com/vaadin/framework/commit/acfd75ee2ec8ad97f8dd54e2ae454257e7284159

as a workaround, you can add a **focusListener** to the DateField, then the blurListener works normally.

**Comment by KatriHaapalinna** [comment] 2019-01-21 12:46
@ZheSun88 
The workaround re-introduces the old issue #1008 that the referenced commit was meant to fix.

**Comment by TatuLund** [comment] 2019-02-14 13:51
We have been looking into this bug, but unfortunately it seems that we cannot fix it in the Framework, and the issue has to be closed as a won't-fix.

The problem is obviously in timing the multiple consecutive focus/blur events in the internal widgets of DateField. The focus/blur events can be fairly well handled inside one component, but it leads to focus handling breaking in more disruptive ways in the wider context (e.g. navigating focus to another component is prevented if popup is open). The component would need a significant rewrite to circumvent this current behaviour, which we have evaluated to be too time-consuming for this issue.

**Closed by TatuLund** 2019-02-14 13:51 UTC
Labels: BFP, wontfix, workaround
