### ISSUE TITLE
Vaadin 8 Grid: cannot activate the buffered inline editor from the server side

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#9513] opened 2017-06-09 09:16 UTC
I'm trying to create a user interface that includes a Grid with buffered inline editing. Rows can only be edited by double-clicking them, but I would like to select a row and then click an Edit button.

There is an editRow() method in com.vaadin.client.widgets.Grid$Editor on the client side, but not in com.vaadin.ui.components.grid.Editor on the server side. There's no editRow() in the EditorClientRpc interface either. Should be added.

For more details see this thread:
https://vaadin.com/forum#!/thread/15977063

**Comment by tsuoanttila** [comment] 2017-06-12 06:15
This ticket is a duplicate of implementation ticket for Grid in Vaadin 8. The current reason for not having that method existing there is a long list of discussions whether it's ok to make a huge performance issue of finding the index of an item, when using an actual backend and not in-memory data.

I'll close this as a duplicate, please follow the two linked tickets for this issue. #8820  and #8477

**Closed by tsuoanttila** 2017-06-12 06:15 UTC
Labels: duplicate
