### ISSUE TITLE
Investigate broken WH

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#8100] opened 2016-12-28 08:26 UTC
Something weird going on in WH (v7) Fill hours tab. When I update any row, the row selection doesn’t work anymore after that util reload.

WHv7 is apparently using 8.0.0.alpha10 nowadays

**Comment by hesara** [comment] 2016-12-29 08:20
Probably wrong repository, and probably caused by WH using equals/hashCode methods that are based on the object id. How this is resolved could lead to some migration documentation additions, thoguh.

**Comment by Artur-** [comment] 2016-12-29 08:38
It is indeed using equals/hashCode based on the object id. Why does Grid or DataProvider break down because of it?

**Comment by elmot** [comment] 2016-12-29 15:02
The bug is reproduced using both alpha10 and beta1.
Requires quite a long list of records.

**Comment by elmot** [comment] 2016-12-29 16:05
The problem is DTO's equals/hashcode. Apparently, KeyMapper does not work as supposed.

**Comment by pleku** [comment] 2017-01-10 14:10
Closed by ae54094346c40be3a058e41c942236383362ffd0

**Closed by pleku** 2017-01-10 14:10 UTC
Labels: bug
