### ISSUE TITLE
Using drag and drop in Vaadin 8 met  null of onDropTargetDetached_0_g$ 

### ISSUE THREAD

**Issue by wiekern** [vaadin/framework#9438] opened 2017-05-25 18:39 UTC
- Vaadin version: Vaadin 8.1.0alpha8
- Description of the bug
According to this demo on official documentation I have written a simple program in which is drag and drop of grid used. There are three Grids which are not only as drag source but also drop target, thus, I can drag one item from any grid of them, and drop it to any of them, even to same grid where it is dragged.

I have got logs under `super dev mode` below . I have tired to find out why there came a null, but it was in vain.
Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'onDropTargetDetached_0_g$' of null
ConsoleLogger.java:32 TypeError: Cannot read property 'onDropTargetDetached_0_g$' of null
    at ILe_g$.BLe_g$ [as onUnregister_0_g$] (DropTargetExtensionConnector.java:137)
    at f0d_g$.y0d_g$ [as unregisterConnector_0_g$] (ConnectorMap.java:182)
    at Pse_g$._se_g$ [as unregisterRemovedConnectors_0_g$] (MessageHandler.java:821)
    at Pse_g$.Tse_g$ [as execute_1_g$] (MessageHandler.java:498)
    at jWd_g$ (ApplicationConfiguration.java:662)
    at ase_g$.pse_g$ [as handleJSON_0_g$] (MessageHandler.java:1501)
    at ase_g$.qse_g$ [as handleMessage_0_g$] (MessageHandler.java:246)
    at Uve_g$.Wve_g$ [as onResponseReceived_0_g$] (XhrConnection.java:166)
    at Ljc_g$.Ojc_g$ [as fireOnResponseReceived_0_g$] (Request.java:250)
    at Vkc_g$.Wkc_g$ [as onReadyStateChange_0_g$] (RequestBuilder.java:412)
    at XMLHttpRequest.<anonymous> (XMLHttpRequest.java:329)
    at OI_g$ (Impl.java:239)
    at RI_g$ (Impl.java:291)
    at XMLHttpRequest.<anonymous> (Impl.java:77)

**Comment by pleku** [comment] 2017-05-26 05:35
Hello. Thanks for the detailed report. When looking at the stack trace, I see that it is probably caused by the same issue as with #9101 and was fixed with #9341 in 8.1.0.beta1.

I'm closing this for now, please test the beta and report back to this ticket if the issue still persists. 
Cheers

**Closed by pleku** 2017-05-26 05:35 UTC
