### ISSUE TITLE
setExpandRatio and setValue breaks layout

### ISSUE THREAD

**Issue by sarahfuchs** [vaadin/framework#10089] opened 2017-09-26 12:34 UTC
Vaadin version: '8.1.4'

Description: I use a double formatter which resets the value with the desired decimal digits. If I use a setExpandRatio this breaks the layout completely and the input field 'jumps' to the right out of sight.

minimal reproducible example:
    com.vaadin.ui.TextField doubleField = new TextField();
    doubleField.addBlurListener(event -> {
      NumberFormat format = NumberFormat.getInstance();
      format.setMinimumIntegerDigits(2);
      double doubleValue = Double.parseDouble(doubleField.getValue());
      doubleField.setValue(format.format(doubleValue));
    });
    Label captionComponent = new Label("Caption");
    HorizontalLayout itemLayout = new HorizontalLayout(captionComponent, doubleField);
    itemLayout.setWidth(100, Unit.PERCENTAGE);

    itemLayout.setComponentAlignment(doubleField, Alignment.MIDDLE_RIGHT);
    // comment out the following line and the problem disappears
    itemLayout.setExpandRatio(captionComponent, 0.9F);

    leftLayout.addComponent(itemLayout);

**Comment by TatuLund** [comment] 2019-11-16 18:21
Closed as duplicate of https://github.com/vaadin/framework/issues/10734

**Closed by TatuLund** 2019-11-16 18:21 UTC
Labels: duplicate
