### ISSUE TITLE
setExpandRatio breaks layout when component is updated

### ISSUE THREAD

**Issue by ivesa** [vaadin/framework#10734] opened 2018-03-20 12:57 UTC
Seen on multiple browsers (Chrome 65.0, FireFox 58.0.2, Safari 11.0.3), with Vaadin 8.3.2.

Setting an expand ratio on a component in a HorizontalLayout works fine initially but when the component is upgraded (for instance: setting value of a ProgressBar or setting the input prompt of a TextField), the component suddenly becomes wider than the HorizontalLayout.

Example code:
```
@Push
public class MyUI extends UI
{
    @Override
    protected void init(VaadinRequest vaadinRequest)
    {
        ProgressBar progress = new ProgressBar();
        progress.setWidth(100, Unit.PERCENTAGE);
        Button button = new Button("Cancel");

        HorizontalLayout layout = new HorizontalLayout(progress, button);
        layout.setExpandRatio(progress, 1);
        layout.setWidth(100, Unit.PERCENTAGE);
        setContent(layout);

        UI ui = UI.getCurrent();
        Executors.newScheduledThreadPool(1).scheduleAtFixedRate(() -> update(ui, progress), 4, 2, TimeUnit.SECONDS);
    }

    public void update(UI ui, ProgressBar progress)
    {
        ui.access(() -> {
            float value = progress.getValue();
            value = (value >= 1) ? 0 : value + 0.1f;
            System.err.println("new value: " + value);
            progress.setValue(value);
        });
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet
    {
    }
}
```

Initial (correct) screenshot:

![before](https://user-images.githubusercontent.com/5013139/37655723-5c904094-2c46-11e8-85c5-29109ffcc1c7.png)

Issue visible after ProgressBar.setValue() call. Note how the Cancel button is pushed out of the layout.
![after](https://user-images.githubusercontent.com/5013139/37655668-39d5f8a0-2c46-11e8-9320-56ab3e4e7896.png)

The same effect can be achieved by replacing the `ProgressBar` with a `TextField` and using `TextField::setPlaceHolder` in the `update` method.

**Comment by TatuLund** [comment] 2019-11-16 18:14
Probably duplicate of https://github.com/vaadin/framework/issues/10808

**Comment by TatuLund** [comment] 2020-03-03 12:52
There is a workaround for the problem by setting suitable expand ratio for both the progress bar and the button:

```
        ProgressBar progress = new ProgressBar();
        progress.setWidth(100, Unit.PERCENTAGE);
        Button button = new Button("Cancel");
        button.setWidth("100%");
        
        HorizontalLayout layout = new HorizontalLayout(progress, button);
        layout.setExpandRatio(progress, 10);
        layout.setExpandRatio(button, 1);
        layout.setWidth(100, Unit.PERCENTAGE);
        setContent(layout);

```

**Closed** 2020-03-09 14:54 UTC
Labels: BFP, workaround
