### ISSUE TITLE
Grid columns width change when displayed within a tabsheet

### ISSUE THREAD

**Issue by yakouch** [vaadin/framework#9819] opened 2017-08-15 08:04 UTC
I'm using vaadin 8.1.1 and I have a tabsheet where a display grid within the tabs.

When the tab is loaded the first time, the width of each column is calculated correctly.

When I switch between the tabs, the width of the column gets shrinked. I beleive that this is a bug.

**Comment by scrmtrey91** [comment] 2017-08-21 09:06
Yeah we noticed that too in dev team in our company. We discover that width get calculated from header cell (content of header cell) instead of grid body row cell content of column.

**Comment by Bugi82** [comment] 2017-08-31 04:41
We noticed same thing. It is still present in Vaadin 8.1.3. It takes witdh of column header and not largest contnent.

**Comment by TatuLund** [comment] 2018-05-04 13:31
Is this duplicate of https://github.com/vaadin/framework/issues/10438 ?

**Comment by tsuoanttila** [comment] 2018-05-04 14:08
This issue is most likely related to Grid not receiving initial data when switching between Tabs in TabSheet. There was a fix for said issue #10872 and should be in `8.5-SNAPSHOT`. Can someone test it? If the issue persists, I would like to get an example UI where this issue happens to speed up the fixing.

**Comment by tsuoanttila** [comment] 2018-05-17 07:48
Issue seems to be fixed. Closing.

**Closed by tsuoanttila** 2018-05-17 07:48 UTC

**Comment by gmerton** [comment] 2019-07-17 18:56
I'm using 8.7.2 and am still having this issue.

**Comment by TatuLund** [comment] 2019-07-22 12:31
> I'm using 8.7.2 and am still having this issue.

Did you just recently upgrade from version before 8.4.2?
