### ISSUE TITLE
Can't scroll with the cursor in the grid in IE

### ISSUE THREAD

**Issue by Seb-as-tien** [vaadin/framework#10639] opened 2018-02-16 13:46 UTC
Hi, I have a problem with Grids, but only In IE. 
When my grid has a scrollbar (Vertical or Horizontal) and I've some content under my Grid, if the cursor of my mouse is on the grid, I can scroll the content of my grid but when I'm to the end of my Grid, I want to scroll to the rest of my page (with my cursor on the grid). 
Is there a way to fix it ?

**Comment by jouni** [comment] 2018-02-20 10:02
This seems like a duplicate of #9477, but you say it only happens in IE for you, which seems odd.

**Comment by TatuLund** [comment] 2018-02-20 10:54
It happens also with Chrome.

**Comment by TatuLund** [comment] 2018-04-04 14:49
This one should be actually now fixed in 8.3.3, see: https://github.com/vaadin/framework/issues/9477

**Closed by TatuLund** 2018-04-04 14:49 UTC
Labels: BFP, bug
