### ISSUE TITLE
Current date is showing after setting range in DateField in MONTH resolution

### ISSUE THREAD

**Issue by AlexByte** [vaadin/framework#11605] opened 2019-05-30 12:31 UTC
- Vaadin Framework version
8.8.2
- Description of the bug
When you set the range for the date field with month resolution, the current month is  displayed in the field. Same bug with year resolution.
- Minimal reproducible example

```
final DateField dateField = new DateField();
dateField.setResolution(DateResolution.MONTH);
    
Button button = new Button("Set range");
button.addClickListener(e -> dateField.setRangeStart(LocalDate.of(2018, 1, 1)));
```
https://github.com/AlexByte/vaadin-datefiled-month-bug/blob/master/src/main/java/org/test/MyUI.java#L30-L34
- Expected behavior
As well as with DAY resolution in the field there should not appear current date after setting the range.
- Actual behavior

![Video-Thu-May-30-2019-15-58-17](https://user-images.githubusercontent.com/25251772/58634388-da248100-82f3-11e9-8f04-aa418d539d5c.gif)
FYI: Field value on server is not changed.
UPD: In vaadin 8.9.0.alpha1 the field value with month and year resolution is changed to current date after setting range!

**Comment by ZheSun88** [comment] 2019-06-04 07:59
Hi @AlexByte ,

Thanks for creating this issue. 
From your description, I can find two different issues:

1) `Current date is showing after setting range in DateField in MONTH resolution`
I have verified this by using the 8.8.2, but I cannot reproduce this issue, same with your GIF image, that `05.19` means `May, 2019`, which should be the current month when you created this ticket.

2) `When you set the range for the date field with month resolution, the current month is displayed in the field. Field value on server is not changed.`
This is not a bug and it works as a design, it is the same for different resolutions like `Day`, `Month` and `Year`, by setting the range doesn't trigger the value change event.

**Comment by AlexByte** [comment] 2019-06-06 12:52
1. Yes, it's current month.
2. I agree.

**Comment by ZheSun88** [comment] 2019-06-06 13:07
Then i will close this ticket. comment here for more discussion.

**Comment by AlexByte** [comment] 2019-06-06 13:56
Why do you close if the bug is not fixed?

> > Current date is showing after setting range in DateField in MONTH resolution
> I have verified this by using the 8.8.2

**Comment by ZheSun88** [comment] 2019-06-07 11:55
what do you mean the current date? As it is shown in the gif you have attached here, there is no Date in the field. Or did i miss something?

**Comment by AlexByte** [comment] 2019-06-07 11:57
Well, the current month is displayed

**Comment by ZheSun88** [comment] 2019-06-07 11:58
I am a bit confused now, Isn't it correct?

**Comment by AlexByte** [comment] 2019-06-07 12:09
IT's not correct, no value should be displayed in datefield in month resolution, as in day and year resolution.

**Comment by ZheSun88** [comment] 2019-06-07 12:33
I just tested with `DateResolution.YEAR` and the current year is shown in the field too. And with `DateResolution.DAY`, there indeed no date is shown. And this is by design and I dont think it is a real bug in this case. 

![date-field](https://user-images.githubusercontent.com/31067185/59104204-9ce67180-8939-11e9-845a-3ba7335cd307.gif)

**Comment by AlexByte** [comment] 2019-06-07 12:36
It means that in the month and year mode this is a bug, what makes you think that this is a design? This leads to a misunderstanding that in fact the value of the field is empty.

**Comment by AlexByte** [comment] 2019-07-03 18:24
Ib vaadin 8.9.0 the value is changed!

**Comment by dyorgio** [comment] 2019-07-12 20:36
@ZheSun88 and @AlexByte 
I think that the problem is that fix is applied in abstract super class, and the original bug only happens in VPopupTimeCalendar (with any time resolution aka. select element changes).

**Comment by AlexByte** [comment] 2019-07-25 13:43
@dyorgio https://github.com/vaadin/framework/pull/11574 fixes another bug

**Comment by AlexByte** [comment] 2019-07-25 13:46
@ZheSun88 Do you think that it’s normal that when you change the range, the datefield value changes?

**Closed** 2020-01-28 10:35 UTC
