### ISSUE TITLE
Grid's DetailGenerator opening row details in random positions

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/framework#11139] opened 2018-08-23 19:46 UTC
- Vaadin Framework version: Tested on 8.5.1
- Browser version: Tested on chrome / IE11 / Firefox / Edge
- Web container name and version: Jetty 9.3.9.v20160517
- Description of the bug:
If you configure a grid with a `DetailsGenerator<T>` and start opening several details at the same time (in the provided example: by clicking on several rows), they start to appear in random parts of the grid. If you try with version 8.4.1 they appear under each row (expected behavior)
- Minimal reproducible example:
[grid-detail-handler-problem.zip](https://github.com/vaadin/framework/files/2315924/grid-detail-handler-problem.zip)
- Expected behavior: Each detail should appear after the related row
- Actual behavior: Details are being opened in random positions.

**Comment by mehdi-vaadin** [comment] 2018-09-18 13:52
I can't reproduce this bug in Chrome 69 and Firefox 61 using the provided example. @mlopezFC would you verify that you can reproduce the bug in your example with the latest versions of browsers? In case the bug is still there, please add a screenshot.

**Comment by strxetics** [comment] 2018-09-21 09:08
https://github.com/vaadin/framework/issues/11185 seems to be a duplicate

**Comment by mehdi-vaadin** [comment] 2018-09-25 07:35
@strxetics Thanks for your comment. I tried resizing the browser; but, I can't still reproduce this bug. 
![grid-detail-generator](https://user-images.githubusercontent.com/32511762/45999450-623ff000-c0ae-11e8-87f1-b29560fbc7f2.gif)
@mlopezFC Would you please comment on this? In what situation do you see this bug?

**Comment by strxetics** [comment] 2018-09-25 11:32
![bug_grid_details](https://user-images.githubusercontent.com/36300788/46011725-1b122900-c0c7-11e8-93d0-1775259b397a.gif)

Here you can see the bug in my component. Happens also when removing custom styles from grid. 

` private fun setUpComponent() {

        setWidth(100f, Sizeable.Unit.PERCENTAGE)

        isHeaderVisible = false

        setSelectionMode(SelectionMode.SINGLE)

        rowHeight = 72.0

        addStyleName("workinstructions-grid")

        setDetailsGenerator(this::getDetailsGenerator)

        columns.forEach { it.setSortable(false) }

    }`

these are the basic settings of the grid

**Comment by strxetics** [comment] 2018-09-25 12:37
CSS: 
```
.workinstructions-grid.v-grid-workinstructions-grid {

  height: calc(100% - #{$sidebar-header-height}) !important;

  .v-grid-cell-focused:before, .v-grid-cell-selected:before, .v-grid-row-selected .v-grid-cell:before {
    background: none !important;
    border-left: transparentize($color-x-blue, 0.8);
  }

  .v-grid-row-selected:before, .v-grid-spacer:before {
    border-left: 5px solid rgba(52, 154, 255, 0.5);
    content: "";
    position: absolute;
    left: 0;
    height: 100%;
    top: 0;
    z-index: 1;
  }

  .v-grid-row-selected .step-title-label.hidden-when-selected {
    display: none;
  }

  .v-grid-row-selected .step-title-textfield {
    display: block;
    pointer-events: all;
  }

  .step-title-textfield {
    display: none;
    font-size: 15px;
    font-weight: 600;
    white-space: normal;
    width: 100%;
  }

  .v-grid-spacer.stripe > td, .v-grid-spacer > td {
    background-color: unset;
    border-top: none;
  }

  .v-grid-cell, .v-grid-cell-focused, .v-grid-cell-selected {
    padding: 0 24px;
    border-bottom: 1px solid $color-table-separator;
    border-color: $color-table-separator !important;
  }

  .v-grid-row, .v-grid-spacer {
    cursor: pointer;
  }

  .v-grid-body .v-grid-row:last-child {
    border-bottom: none;
  }

  .v-grid-row:nth-child(even) .v-grid-cell {
    background: none !important;
  }

  .v-grid-cell-focused .workinstruction-grid-step-layout {
    .bottomBorder {
      border-bottom: 1px solid $color-x-blue;
    }
  }

  .v-grid-tablewrapper .v-grid-cell .component-wrap {
    pointer-events: none;
  }

  .details-Layout {
    padding: 0px 24px 0 15px;

    .details-button {
      font-weight: 600;
      text-transform: uppercase;
      font-size: 13px;
      color: $color-x-blue;
    }

    .details-label {
      color: $color-middle-grey;
      font-size: 13px;
    }
  }

  .workinstruction-grid-step-layout {
    height: 72px !important;
    width: 100%;

    .v-slot-workinstruction-thumbnail {
      height: 56px;
      padding-top: 8px;

      .workinstruction-thumbnail {
        box-shadow: $material-box-shadow;
        object-fit: cover;
      }
    }

    .step-title-label {
      font-size: 15px;
      font-weight: 600;
      white-space: normal;
    }

    .index-title-label {
      padding-top: 8px;
      font-size: 11px;
      color: $color-middle-grey;
      font-weight: 600;
      text-transform: uppercase;
    }

    .bottomBorder {
      width: 100%;
      border-bottom: 1px solid $color-table-separator;
      height: 24px;
    }

  }
}
```

Kotlin getDetailsGenerator:

```
    private fun getDetailsGenerator(stepInstruction: StepInstructionDTO): Component {
        val fakeDetailsButton = Label(Messages.getString("ProductStepParameterEditWindow.details.caption")).apply {
            addStyleName("details-button")
        }

        val detailsLabel = Label(workInstructionsVM.getDetailStepSummaryString(stepInstruction)).apply {
            addStyleName("details-label")
        }

        return VerticalLayoutFactory.fullSizedNoSpaceNoMargin(detailsLabel).apply {
            addStyleName("details-Layout")
            if (workInstructionsVM.isImageStep(stepInstruction)) {
                addLayoutClickListener {
                    workInstructionsVM.stepInstructionsDetailsVisible.set(true)
                }
                addComponent(fakeDetailsButton)
            }
        }
    }
```

There is more custom css applied though. For example we are using the [Material Theme](https://github.com/appreciated/material)

And it also happens in different grids which are not using the workinstructions-gird class.

I will try your code.

**Comment by strxetics** [comment] 2018-09-25 12:44
I tested it, the same thing happens with your code if i run it in the same tabsheet.

**Comment by mlopezFC** [comment] 2018-09-25 13:41
Hi! ... sorry for taking so long to answer. Still getting the same behavior with Chrome Version 69.0.3497.100 (Build oficial) (64 bits), and Firefox 62.0.2 (64-bit).
Here's an animated GIF showing the problem:
![griddetailhandlerproblem](https://user-images.githubusercontent.com/28312758/46018048-5f91ca80-c0af-11e8-92f0-6d36fc10d7ce.gif)

**Comment by TatuLund** [comment] 2018-09-25 16:47
I was following the discussion here. The final fix for this issue is actually still stuck in review process https://github.com/vaadin/framework/pull/11154

**Comment by strxetics** [comment] 2018-09-27 08:39
@mehdi-vaadin @TatuLund  so what does this mean? Will it be fixed soon? Otherwise we will have to revert to an earlier version.

**Comment by TatuLund** [comment] 2018-09-27 10:28
@strxetics We are sorry that you have been forced to wait this fix. I think we should be able to merge it next week.

**Comment by strxetics** [comment] 2018-09-27 10:58
@TatuLund thanks for the heads up, then it should not be a problem :)

**Comment by ZheSun88** [comment] 2018-10-01 10:38
@mlopezFC PR #11154 has been merged and issue with this ticket has been verified and solved. I am going to close this issue, feel free to comment on this ticket if the problem still occurs. 

@strxetics could you verify with the ticket you mentioned there?

**Closed by ZheSun88** 2018-10-01 10:38 UTC
Labels: BFP

**Comment by strxetics** [comment] 2018-11-06 13:23
still happening in 8.6.0

**Comment by harrwiss-swt** [comment] 2019-09-05 10:25
Looks good now in 8.9.0.beta3 - see issue  #11288
