### ISSUE TITLE
Website SSL misconfigured

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/framework#10117] opened 2017-09-29 15:51 UTC
I can't link to your javadoc due to a misconfigured website.

```
$ wget https://vaadin.com/api/package-list
--2017-09-29 10:49:25--  https://vaadin.com/api/package-list
Resolving vaadin.com... 104.20.35.243, 104.20.36.243, 2400:cb00:2048:1::6814:23f3, ...
Connecting to vaadin.com|104.20.35.243|:443... connected.
ERROR: certificate common name `*.vaadin.com' doesn't match requested host name `vaadin.com'.
To connect to vaadin.com insecurely, use `--no-check-certificate'.

```

**Comment by Haprog** [comment] 2017-09-29 16:04
I can't reproduce.
```
$ wget https://vaadin.com/api/package-list
--2017-09-29 19:02:28--  https://vaadin.com/api/package-list
Resolving vaadin.com... 104.20.36.243, 104.20.35.243, 2400:cb00:2048:1::6814:23f3, ...
Connecting to vaadin.com|104.20.36.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4929 (4.8K) [application/octet-stream]
Saving to: ‘package-list’
```

Also when visiting the site https://vaadin.com with Chrome, it says the site is secure and HTTPS is valid. When viewing cert info it does contain both `*.vaadin.com` and `vaadin.com`.

**Comment by pleku** [comment] 2017-09-29 16:17
I was not also able to reproduce this. I'm closing this now, since this is not really a framework issue anyway. there is a feedback form on vaadin.com (at least on the bottom of the frontpage). 

If you want to, you can still comment here though on this matter

**Closed by pleku** 2017-09-29 16:17 UTC

**Comment by archiecobbs** [comment] 2017-09-29 17:37
Interesting... it looks like this is just a bug in `wget`. With `wget 1.12` it fails but after upgrading to `wget 1.16` it works.

Sorry for the noise.
