### ISSUE TITLE
Grid filter looses focus after DataProvider is reloaded

### ISSUE THREAD

**Issue by AscendingEagle** [vaadin/framework#11080] opened 2018-07-20 11:40 UTC
I have a Grid where each Column has a TextField that acts as a filter. The grid has a registered DataProvider as the data source.

```
Grid<T> grid = new Grid<>();
DataProvider<T, M> dataProvider = ...;
```

When the text in the TextField is changed I call:
`grid.getDataProvider().refreshAll();`

When the column filter is changed the elements in the grid are changed accordingly. However, when the amount of visible rows change from "too many to fit in one page" to "too few to fill one page" the column filter looses focus.

For example:
- The grid contains 10000 elements and the filter reduces it down to 1000. As a result the focus is NOT lost.
- The grid contains 10000 elements and the filter reduces it down to 10. As a result the focus IS lost.

There is no reason why this should happen. It is a major problem because the user keeps typing without noticing that the focus is lost.

- Vaadin Framework version: 8.5.1
- Browser version: Chrome, Firefox, Edge, IE, Safari
- Web container name and version: Tomcat 9

**Comment by Kalomo** [comment] 2018-08-06 10:45
i can confirm that, its very annoying!

**Comment by TatuLund** [comment] 2020-03-12 08:12
This is indeed annoying. 

I have not yet had to test this. But I would assume that as workaround you should be able to return the focust the text field by calling textField.focus() in the end of the value change event after Grid has been updated.

**Comment by TatuLund** [comment] 2020-05-13 15:53
We did some testing and actually could not find way to reproduce the issue. Either some fix in newer versions have fixed this as byproduct or the replication method is not obvious. So I am closing this as cannot reproduce. If someone still can reproduce this and attach test application that replicates the issue, we can re-open.

**Closed by TatuLund** 2020-05-13 15:53 UTC
Labels: cannot reproduce
