### ISSUE TITLE
Grid details stays sometimes hidden when shoud be visible

### ISSUE THREAD

**Issue by lubomirmatus** [vaadin/framework#10517] opened 2018-01-11 11:31 UTC
Running on Windows 7 x64 + TomEE 7, tested with Vaadin versions 8.1.6, 8.1.7 and 8.2.0, and browsers Chrome 63.0.3239.132, Firefox 57.0.4, IE 11.

I have grid with many rows (hundreds), data from `DataProvider`. I set some of the rows to have details visible using `grid.setDetailsVisible(item, true)`.
When I scroll down to see these rows, the details are not visible. There is only a thin gap between rows.
When I check the DOM structure, there are many `<tr class="v-grid-row v-grid-row-has-data">` elements and one `<tr class="v-grid-spacer stripe">` right after row that should have details visible. The `v-grid-spacer` `tr` element with `height` only `3px`.
The details layout is composed as `GridLayout` inside `VerticalLayout`. The `divs` of `v-gridlayout-slot` class has all `height`, `top`, `width`, `left` properties set to `0px`.

When I try to change column width with draging the column header spacer by mouse, when I release the mouse button, then the details are shown rendered correctly. Also the position properties of `v-gridlayout-slot` `div` elements are changed to correct values.
But when I scroll the row and details out of screen and then scroll back to that row, the details are again hidden (often).

![1](https://user-images.githubusercontent.com/25178908/34823351-5c85113a-f6ca-11e7-87a9-39425f3d59c1.png)
![2](https://user-images.githubusercontent.com/25178908/34823352-5ca60d36-f6ca-11e7-84bf-3f733f0e2349.png)

**Comment by wbadam** [comment] 2018-01-11 12:53
Possible duplicate of #10300

**Comment by henrizzle** [comment] 2018-02-05 15:24
I had the same problem. I had fix it with setting a fix height to the component that will displayed in the details.

I think this is a bug in the grid!

**Comment by TatuLund** [comment] 2019-12-06 20:16
This should be fixed in Vaadin 8.9.0

**Closed by TatuLund** 2019-12-06 20:16 UTC
Labels: bug
