### ISSUE TITLE
ComboBox dropdown shows only the selected value

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8684] opened 2017-02-24 12:25 UTC
To reproduce:

1. Open a ComboBox and select a value
2. Focus the text field and press arrow left

Expected:
1. The cursor moves left one character
2. If you blur the combo box and click the dropdown button, the options of the combo box are shown
3. You can clear the field to show all options using cmd-a (ctrl-a) and by pressing delete

Actual:
1. The cursor moves left and then back
2. The dropdown only contains the selected item and nothing else
3. Pressing cmd-a selects all text and immediately deselects it (on keyup)

Version: 8.0.0

**Comment by roquefernandez** [comment] 2017-04-03 13:02
Is there any progress on this issue?
We faced this issue also in version 8.0.5

**Comment by mvysny** [comment] 2017-04-10 08:55
[vaadin-app.zip](https://github.com/vaadin/framework/files/909513/vaadin-app.zip)
Added a test project which reproduces the issue. Just press the "Reset" button, select an item from the ComboBox and then try:
1. press left arrow
2. press Ctrl+A to select the whole value. Expected behavior: the value is selected and the user can e.g. copy it to the clipboard. Actual behavor: nothing is selected.
3. Press Shift+Left Arrow: Expected behavior: last character is selected. Actual behavor: nothing is selected.

**Comment by SomMeri** [comment] 2017-11-10 15:44
The issue is present in 8.1.6 too. Other details:
* Press home: the cursor in front and quickly back. It should stay in front.
* Press  shitft+home: the cursor in front and everything is briefly selected. Then the cursor jumps back and everything is deselected again. Pop-up shows up with one option in it.

**Comment by TatuLund** [comment] 2018-04-14 12:58
Still happens in 8.3.3

**Comment by TatuLund** [comment] 2018-09-11 15:56
I could not replicate this anymore, probably fixed by https://github.com/vaadin/framework/pull/11031

**Closed** 2018-09-11 15:56 UTC
Labels: bug
