### ISSUE TITLE
grid::.setMinimumWidth not take effect if grid's width more then screen's width

### ISSUE THREAD

**Issue by andreika63** [vaadin/framework#9432] opened 2017-05-25 09:39 UTC
- Vaadin version 8.0.6
When grid does not fit by width in screen (if we see horizontal scrollbar), setting minimum width on column not take effect.

**Comment by Artur-** [comment] 2017-05-25 10:08
Is this the same issue as #8548 ?

**Comment by andreika63** [comment] 2017-05-25 12:07
May be....
Me problem is that I want to do that user can't change column width less then inner component. 
(i use text field for filtering).
And I've found if grid have scrollbar - min width igrored.

**Comment by hesara** [comment] 2017-05-31 06:22
#8548 is now resolved in the latest 8.1-SNAPSHOT in case you want to test it. Note that you need to call Grid.setMinimumWidthFromContent(false) to enable the mode of operation you want.

**Comment by hesara** [comment] 2017-06-21 08:59
As there are no indications to the contrary, considering this to be a duplicate of #8548.

**Closed by hesara** 2017-06-21 08:59 UTC
