### ISSUE TITLE
InlineDateTimeField shows incorrect minutes and seconds when in readOnly state

### ISSUE THREAD

**Issue by arivanajoki** [vaadin/framework#11268] opened 2018-10-22 13:33 UTC
- Vaadin Framework version :8.5.2
- Browser version :Firefox 62.0.3 (64-bit), Safari 12.0 ...
- Web container name and version : WildFly 14.0.1.Final
- Description of the bug : when InlineDateTimeField is set to readOnly , minutes (and seconds )are displayed as zero 
- Minimal reproducible example: Can be reproduced with Vaadin sampler https://demo.vaadin.com/sampler/#ui/data-input/dates/date-picker just select date and time , then select Read Only checkbox .
- Expected behavior: minutes and seconds are displayed according actual selection
- Actual behavior: minutes and seconds are displayed as zero

**Comment by knoobie** [comment] 2018-10-22 17:31
Sounds like a duplicate of https://github.com/vaadin/framework/issues/6565 - should be fixed in 8.6.0

**Comment by anasmi** [comment] 2018-10-23 06:13
Hi @knoobie , have you tested the issue with 8.7-SNAPSHOT? Can you still reproduce it?

If so, could you, please, share the minimal reproducible example?

**Closed** 2018-10-24 08:30 UTC
