### ISSUE TITLE
Tree refuses to expand node in depth 6 

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11737] opened 2019-09-30 12:44 UTC
#### Basic info:
- Vaadin Framework version: 8.9.0
- Browser version: edge, chrome, firefox, both on linux and windows
- Web container name and version: jetty from archete app

#### Description of the bug
I have tree with nodes collapsed by default. Clicking the arrow expands the node, until I get to dept 6 and then clicking on arrow does nothing. The node does not react at all and client-server request is not sent. 

The only way to open the node on level is is to close its parent and reopen it. After that, node 6 can be expanded. Following nodes can be expanded up to level 26 where the same issue appears.

#### Minimal reproducible example
The example creates tree where each node has one child. Tree items labels correspond to the dept of the node.

UI:
````java
@SuppressWarnings("serial")
@Theme("v8bugstheme")
public class Vaadin8BugsUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        InfiniteTreeLoadDemo infiniteTreeLoadDemo = new InfiniteTreeLoadDemo();
        infiniteTreeLoadDemo.createV8Demo(layout);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "Vaadin8BugsUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = Vaadin8BugsUI.class, productionMode = false)
    public static class Vaadin8BugsUIServlet extends VaadinServlet {
    }
}
````

Data provider:
````java
@SuppressWarnings("serial")
public class InifiniteOneChildDataProvider extends AbstractBackEndHierarchicalDataProvider<Integer, Void> {

	@Override
	public int getChildCount(HierarchicalQuery<Integer, Void> query) {
		Integer parent = query.getParent();
		if (shouldHaveKids(parent))
			return 1;

		return 0;
	}

	@Override
	public boolean hasChildren(Integer parent) {
		if (shouldHaveKids(parent))
			return true;

		return false;
	}

	@Override
	protected Stream<Integer> fetchChildrenFromBackEnd(HierarchicalQuery<Integer, Void> query) {
		Integer parent = query.getParent();
		System.out.println("Fetching for: " + parent);
		
		if (parent != null)
			return Stream.of(parent + 1);

		return Stream.of(1);
	}

	private boolean shouldHaveKids(Integer parent) {
		return parent == null || parent < 5000;
	}

}
````

##### Expected behavior
I can expand nodes up to the infinite depth.

#####  Actual behavior
I can expand nodes up to the depth 6. Then it stops.

**Comment by TatuLund** [comment] 2019-10-19 10:34
This looks like duplicate of this one https://github.com/vaadin/framework/issues/11749

**Comment by TatuLund** [comment] 2019-10-27 09:01
Fixed by https://github.com/vaadin/framework/pull/11753

**Closed by TatuLund** 2019-10-27 09:01 UTC
Labels: duplicate
