### ISSUE TITLE
Grid column selector popup jumps to top scroll position on IE 11

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/framework#10521] opened 2018-01-11 12:47 UTC
### Description
Grid has the hamburger icon on top right corner that opens the column selector popup. This popup will behave badly on IE 11 when the list has scrollbars and user tries to select an item that is scrolled down.

### Expected outcome
Scroll position should not change.

### Actual outcome
When hovering mouse on top of an item in popup the scroll position is reset unexpectedly to top position making it impossible to select the item.

### Live Demo
https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features

### Steps to reproduce
1. Resize browser so that selector popup will introduce vertical scrollbar.
2. Scroll down and try to choose an item that was initially not visible
3. When hovering on top that item, scroll position jumps to top and you are unable to choose that item.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [X] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by elmot** [comment] 2018-06-11 07:06
Still valid.

**Comment by TatuLund** [comment] 2019-12-06 20:22
This is duplicate of https://github.com/vaadin/framework/issues/11245 and https://github.com/vaadin/framework/issues/7874 (closed as wont fix)

**Closed by TatuLund** 2019-12-06 20:22 UTC
Labels: duplicate
