### ISSUE TITLE
Vaadin 8 (versions up to 8.6.0.beta1) not compatible with Liferay CE 7.1.0 GA1

### ISSUE THREAD

**Issue by ctliv** [vaadin/framework#11222] opened 2018-10-05 08:42 UTC
Impacted versions: ALL 
(tested with [8.5.2](http://central.maven.org/maven2/com/vaadin/vaadin-server/8.5.2/vaadin-server-8.5.2.jar) and [8.6.0.beta1](http://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-server/8.6.0.beta1/vaadin-server-8.6.0.beta1.jar))

As listed in Import-Package section of MANIFEST.MF, Vaadin Server imports:

`com.liferay.portal.kernel.util;resolution:=optional;version="[7.0,8)"`

Liferay CE 7.1.0 GA1 is built upon [com.liferay.portal.kernel version 3.6.2](http://central.maven.org/maven2/com/liferay/portal/com.liferay.portal.kernel/3.6.2/com.liferay.portal.kernel-3.6.2.jar) which in its MANIFEST.MF (weirdly) exports:

`com.liferay.portal.kernel.util;version="8.0.0"`

As version 8 is explicitly excluded from Vaadin Server Import-Package section, Vaadin Server is not started by the OSGi runtime and remains in "Installed" state.

Proposed solution is to change Import-Package section of Vaadin Server starting from version 8.6.0 to import:

`com.liferay.portal.kernel.util;resolution:=optional;version="[7.0,9)"`

**Comment by TatuLund** [comment] 2019-03-04 10:33
I think this is duplicate of https://github.com/vaadin/framework/issues/11156 and is fixed now.

Also documentation was updated here: https://vaadin.com/docs/v8/framework/portal/portal-osgi.html

**Closed by TatuLund** 2019-03-04 10:33 UTC
Labels: bug
