### ISSUE TITLE
Clicks broken because of changes to AbstractGridMouseEvent

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#9603] opened 2017-06-28 12:59 UTC
Originall reported by @Snap252 in https://github.com/vaadin/framework/pull/9062

the new implementation of 

	com.vaadin.client.widgets.Grid.AbstractGridMouseEvent.getGrid()

will return null in subclasses of 

	com.vaadin.client.widgets.Grid<JsonObject>

so it is a major bug for us because clicks don't work any more

example:
class1:

	@Connect(EditorGrid.class)
	public class EditorGridClientConnector extends GridConnector {
	
		@Override
		public EditorClientGrid getWidget() {
			return (EditorClientGrid) super.getWidget();
		}
	}

class 2:

	import elemental.json.JsonObject;
	
	public class EditorClientGrid extends com.vaadin.client.widgets.Grid<JsonObject> {
		public EditorClientGrid() {
		}
	}

**Comment by Snap252** [comment] 2017-07-13 08:16
Are there any news here?

**Comment by tsuoanttila** [comment] 2017-07-18 11:03
Hi @Snap252,

We made a change that I think should've address at least parts of this problem in #9283 . Have you tested this issue with the 8.1 pre-release versions of Vaadin?

**Comment by Snap252** [comment] 2017-08-02 06:14
Thx 4 the response.
We are using the Vaadin7 Branch . And afaik there are no more nightly builds / pre-releases to test it.

Will this fix be merged?

Kind regards

**Comment by sialhant** [comment] 2017-08-16 06:51
Hi,
are there any plans to merge the fix into the Vaadin7 branch? This is important information as the issue is critical for us and we must decide on how to go on.  
Thank you!

**Comment by hesara** [comment] 2017-10-10 08:31
Addressed in 7.7 by #10144.

**Closed by hesara** 2017-10-10 08:31 UTC
