### ISSUE TITLE
DateField / DateTimeField value change event trigerred too late

### ISSUE THREAD

**Issue by mg-dev** [vaadin/framework#11316] opened 2018-11-14 11:27 UTC
Simple scenario using Vaadin 8.6.0 (tested also on 8.5.2) archetype project:

Button and DateTimeField (resolution SECOND)

Button has clickListener DateTimeField has valueChangeListener
1. Open calendar popup
2. Change one of time dropdowns (hour / minute / second)
3. Click on button (do not click anywhere else, do not blur date field!)

Events received:
1. Button pressed
2. DateTimeField value changed

Above wrong order causes a lot of complications.

When we use TextField (with Value change on BLUR) instead DateTimeField events received:

1. TextField value change
2. Button pressed

Code to reproduce:
>         final VerticalLayout layout = new VerticalLayout();
>         
>         DateTimeField dateField = new DateTimeField();
>         dateField.setResolution(DateTimeResolution.SECOND);
>         dateField.addValueChangeListener(event -> {
>         	System.out.println("Date field value: " + event.getValue());
>         });
>         
>         Button button = new Button("test");
>         button.addClickListener(ev -> {
>         	System.out.println("Clicked!");
>         });
>         
>         layout.addComponents(button, dateField);
>         setContent(layout);

**Comment by sevenzebras** [comment] 2019-04-13 15:07
The problem is still present in Vaadin Framework 8.7.2.

**Comment by anasmi** [comment] 2019-04-15 09:02
Hi,

this actually works as designed and described here: https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java#L53

>The datefield will now only set the date variables while the user is selecting year/month/date/time and not send them directly. Only when the user closes the popup (by clicking on a day/enter/clicking outside of popup) then the new value is communicated to the server. In this particular case, the button click indeed happens before the pop-up is closed, so it's an expectable behavior.

**Comment by anasmi** [comment] 2019-04-15 09:02
Or have I missed something from the description?

**Comment by TatuLund** [comment] 2019-05-09 08:36
Discussion the on PR #11542 in short. The fix is not working in all cases, with some computers it does give good results, but depending on corner cases of the timing, it is not working in all cases.

**Comment by ZheSun88** [comment] 2019-05-15 11:21
this bug will be fixed with #11574 and the patch will be shipped with a minor update. probably with 8.9.0 in this case (rough estimate will be in July, 2019)

**Closed** 2019-06-14 12:31 UTC
Labels: BFP
