### ISSUE TITLE
Vaadin 8.5.2 drag and drop grid headers columns are not working on google chrome

### ISSUE THREAD

**Issue by rodrifmed** [vaadin/framework#11192] opened 2018-09-18 22:06 UTC
EDITED -> CHANGED VERSION 8.5.3 to 8.5.2

Hi @pleku I just updated here my project to vaadin bom 8.5.2 and the problem still
I`m running the project in

Vaadin version: 8.5.2
SO: Ubuntu 18.04.1 LTS,
Browser: Chrome Version 69.0.3497.92 (Official Build) (64-bit)
IDE: Eclipse Photon Release (4.8.0)
To create the grid Im using a ObjectNode class from Jackson Json library. So I need to create the columns with the addColumn using ValueProvider. And Im using addColumnReorderListener to store the position of the columns everytime the user drag and drop the columns.

Do you need more detail?

**Comment by elmot** [comment] 2018-09-19 07:37
> bom 8.5.3

One can not simply upgrade a project to 8.5.3 because there is no one yet.

**Comment by rodrifmed** [comment] 2018-09-19 16:07
Sorry my friend, correcting here -> Vaadin 8.5.2

**Comment by TatuLund** [comment] 2019-11-16 19:19
Closed as duplicate of https://github.com/vaadin/framework/issues/11236

**Closed by TatuLund** 2019-11-16 19:19 UTC
Labels: duplicate
