### ISSUE TITLE
Make the API for disallowing user selection in Grid easy to use

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8150] opened 2017-01-05 13:27 UTC
Based on the usage example in https://github.com/vaadin/framework/blob/master/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L441, you are supposed to check if the selection model is of a given Impl class, then not even cast it to the class but instead call another method in Grid (`asMultiSelect()`, which is documented as `User this grid as a multiselect in Binder`) and then use the return value to call `setReadOnly(true)` to not allow user selection.

In what world is this intuitive?

**Comment by denis-anisimov** [comment] 2017-01-05 13:37
Don't we already have similar ticket created by @Legioth ?

The original idea was to support "read-only" in HasValue.
The only way to get `HasValue` from a `Grid` is the representations (multi and single select).
That's why it's done it that way.

Having the selection disallowance feature is completely different thing (though the impl is the same and is already there).
And this has been discussed. I'm pretty sure there is a request from Leif about this.

**Comment by pleku** [comment] 2017-01-07 13:53
Duplicate of https://github.com/vaadin/framework8-issues/issues/546 and my opinion is still the same as in there. Though if we move methods from SelectionModel to Grid, like select, getSelected, this might be another one of those.

**Comment by Legioth** [comment] 2017-01-09 08:34
What the user wants to do is: `myGrid.getSelectionModel().setUserSelectionAllowed(true);`

The user does not want to have to know that they have to do `HasValue.setReadOnly(false)` on the return value of either  `asSingleSelect()` or `asMultiSelect()` (depending on how the grid is otherwise configured).

**Comment by pleku** [comment] 2017-01-10 09:40
Closing as duplicate of  vaadin/framework8-issues#546

**Closed by pleku** 2017-01-10 09:40 UTC
