### ISSUE TITLE
Vaadin 8.0.x -- atmosphere-runtime-2.4.5.vaadin2.jar -- incompatible with Jetty 9.4.x

### ISSUE THREAD

**Issue by Augar** [vaadin/framework#9127] opened 2017-04-21 07:05 UTC
**Affected vaadin version(s):**
- Vaadin 8.0.3
- Vaadin 8.0.4
- Vaadin 8.0.5

**Bug scenario:**
Activate atmosphere via the @PUSH annotation
Run your vaadin application on Jetty 9.4.x
-> You will get a "Session expired"as soon as you start a browser session
See according Vaadin Forum thread: https://vaadin.com/forum#!/thread/15523853
We did not encounter this problem using tomcat.

**Possible source:**
In Vaadin 8.0.3 there has been an update of the atmosphere framework
https://github.com/vaadin/framework/commit/0f08e30f6e735716f6bb4135c22103c2b65911aa
which might be a clou to our Jetty problem.
atmosphere.runtime.version **2.4.5.vaadin2**

**Summary:**
Using Jetty 9.4.x + Vaadin 8.0.3/8.0.4/8.0.5 + @PUSH -> immediate "Session expired"
Using Jetty 9.4.x + Vaadin 8.0.2 + @PUSH -> works fine
Using Jetty 9.3.x + Vaadin 8.0.3/8.0.4/ + @PUSH -> works fine

**Comment by Artur-** [comment] 2017-04-21 08:38
Does this work if you specify `transport=LONG_POLLING`? If I remember correctly the early 8.0 versions had a problem with websockets and were practically always falling back to long polling. If this is the case, then the problem is really that Jetty 9.4 + websockets do not work, which is #8134

**Comment by Augar** [comment] 2017-04-24 10:45
We just tested this issue and you are absolutely right.
If we switch over to _LONG_POLLING_ our application works.

**Our code - using WEBSOCKET (not working)**
```
@Theme("my_valo")
@SuppressWarnings("serial")
@PreserveOnRefresh
@Push(
         value = PushMode.AUTOMATIC,
         transport = Transport.WEBSOCKET)
public class MyUI extends UI
{
```


**Our code - using LONG_POLLING (working)**
```
@Theme("my_valo")
@SuppressWarnings("serial")
@PreserveOnRefresh
@Push(
         value = PushMode.AUTOMATIC,
         transport = Transport.LONG_POLLING)
public class MyUI extends UI
{

```

Hopefully this bug is not to hard to find/fix :-)

**Comment by Artur-** [comment] 2017-04-24 12:12
Let's close this then. You can track #8134 for progress on supporting Jetty 9.4 websockets and a workaround is to downgrade to Jetty 9.3

**Closed by Artur-** 2017-04-24 12:12 UTC
