### ISSUE TITLE
One constructor of Button fails to register RPC

### ISSUE THREAD

**Issue by markathomas** [vaadin/framework#10599] opened 2018-02-02 23:12 UTC
- Vaadin Framework version:
at least 8.2.1+

- Description of the bug:
Constructor of button:
`public Button(Resource icon, ClickListener listener) {
        setIcon(icon);
        addClickListener(listener);
    }`
fails to call `this()` resulting in no registration of ServerRpc

**Comment by knoobie** [comment] 2018-02-03 16:44
See #10566

**Comment by Legioth** [comment] 2018-02-19 10:59
Duplicate of https://github.com/vaadin/framework/issues/10540

**Closed by Legioth** 2018-02-19 10:59 UTC
Labels: duplicate
