### ISSUE TITLE
The selected entry is not always displayed / selected in the dropdown menu.

### ISSUE THREAD

**Issue by web-padawan** [vaadin/framework#11322] opened 2018-11-19 09:13 UTC
_From @tDD01069 on November 16, 2018 13:13_

### Description
The selected entry is not always displayed / selected in the dropdown menu.

### Example
https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box

If I select "ANGOLA", "ANGOLA" is also selected in the drop-down menu after collapsing and reopening. 
When I select "BERMUDA", after collapse and reopen, I see the first 10 entries - without "BERMUDA".
Why is not the page with BERMUDA and its selection displayed?

_Copied from original issue: vaadin/vaadin-combo-box#747_

**Comment by web-padawan** [comment] 2018-11-19 09:13
The version demonstrated on that page is related to the older version of Vaadin Framework 8.
This is a repository for the web component used by Vaadin platform V10+
Moving the issue to the appropriate repository now so the team could handle it further.

**Comment by TatuLund** [comment] 2018-11-25 08:46
I think this is duplicate of this issue https://github.com/vaadin/framework/issues/11320

**Comment by TatuLund** [comment] 2020-02-09 16:03
This is not a bug. In Sample Scroll To Selected Item is not checked by default. In Java there is equivalent API to control the behavior. When true, ComboBox will show the page where the selected item is

![image](https://user-images.githubusercontent.com/14309836/74105427-45527280-4b66-11ea-8d40-ce871abc9559.png)

**Closed by TatuLund** 2020-02-09 16:03 UTC
Labels: question
