### ISSUE TITLE
Grid drag & drop with MobileHtml5Dnd

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#11219] opened 2018-10-03 08:23 UTC
Mentioned in #9974:

> Vaadin framework 8.1.7. Linux Ubuntu 16.04 Chrome 63
> With setMobileHtml5DndEnabled(true) , on a Grid, we can drag only the first element.
> I can reproduce the problem on "https://demo.vaadin.com/sampler/#ui/drag-drop/grid-reorder-rows-html5".

and related to the same:
> Can reproduce still. This makes the Grid DnD feature really unusable on (some) Win10 computers.

I cannot reproduce the issue on a non-touchscreen Windows 10 laptop, so the issue needs to be tested with touchscreen device.

**Comment by drewoko** [comment] 2018-10-03 10:57
We also mentioned D&D problems with touchscreen laptops. 

Prioritized issue in Warranty .

**Comment by drewoko** [comment] 2018-10-03 14:59
We tried FF and Chrome

**Comment by OlliTietavainenVaadin** [comment] 2018-10-04 13:31
Demo project that reproduces the issue: https://github.com/OlliTietavainenVaadin/grid-drag-demo

**Comment by ZheSun88** [comment] 2018-11-05 09:50
from @sarahfuchs 

```
For our project the problem can be summarized as follows:
vaadin version 8.6.0
used code: grid with drag & drop
Classes Grid, GridDropTarget, RowMoveListener
Bug: on Notebook touch, IE the drag&drop does not work.
The notebook touch is: Suface Pro 4, Windows 10
Other setups (IE on a PC or Chrome on Notebook touch) are working fine

Our code base is quite large. If you need specific Code snippets, please let me know.
Since its only the customer who works wich Notebook touch its complicated to write a simple test case.
```

**Comment by ZheSun88** [comment] 2018-11-05 11:44
Hi @sarahfuchs, I have tested with a few sample projects (including the one in this ticket) on a Surface with Win10. it looks the drag and drop which is triggered by the mouse event works correctly, but with touch event, it doesn't work. 
will do more investigations.

**Comment by sirbris** [comment] 2018-11-27 09:39
any news on that issue? some of our customers are still experiencing problems with drag&drop on touch devices (seems to be only a problem with Win10)

**Comment by ZheSun88** [comment] 2019-01-11 13:40
What kind of device are they using? and what kind of scenario are they facing? 
`regardless of the browser` sounds quite bad .

**Comment by TatuLund** [comment] 2019-01-29 08:07
After long investigation we have not been able to find the root cause of this, and no reproducing example and setup is available. It is clear that something is probably causing issues with in selected corner cases. It is most likely problem in the polyfill used, i.e. https://github.com/timruffles/mobile-drag-drop It is noted that framework uses older version https://github.com/vaadin/framework/blob/master/server/src/main/resources/VAADIN/drag-drop-polyfill.min.js We tried newer version before Christmas, but it did not help. So I cam closing this as wontfix for now. We may revisit this if there is progress in polyfill library used and need to update the version used.

**Closed by TatuLund** 2019-01-29 08:07 UTC
Labels: BFP, bug, question, wontfix
