### ISSUE TITLE
Bean not updated in Binder with validator

### ISSUE THREAD

**Issue by edler-san** [vaadin/framework#11283] opened 2018-10-30 14:32 UTC
Vaadin versions tested 8.4.5, 8.5.2, 8.6-SNAPSHOT, 8.7-SNAPSHOT

This bug is _very_ similar to #11276 and I suspect they have the same root cause - nevertheless adding it here for completeness.

To reproduce : 
Set 2018/10/29 to first field
Set 2018/10/28 to second field
Set 2018/10/27 to first field, and click Show bean, the value is : 
fromDate: 2018/10/29 
toDate : null

Expected:
                 fromDate: 2018/10/27
                     toDate: 2018/10/28 

Example code

```
package com.vaadin;

import java.time.LocalDate;
import java.util.Objects;

import javax.servlet.annotation.WebServlet;

import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.Binder;
import com.vaadin.data.validator.DateRangeValidator;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;

@Theme("mytheme")
public class MyUI extends UI {

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		HorizontalLayout horizontalLayout = new HorizontalLayout();

		Binder<FromToModel> fromToModelBinder = new Binder<>();
		fromToModelBinder.setBean(new FromToModel());

		DateField fromField = new DateField();
		fromField.setDateFormat("yyyy/MM/dd");

		DateField toField = new DateField();
		toField.setDateFormat("yyyy/MM/dd");

		DateRangeValidator fromRangeValidator = new DateRangeValidator("Range not valid", null, null);
		DateRangeValidator toRangeValidator = new DateRangeValidator("Range not valid", null, null);

		final Binder.Binding<FromToModel, LocalDate> fromBinding = fromToModelBinder.forField(fromField)
				.withValidator(fromRangeValidator).bind(FromToModel::getFromDate, FromToModel::setFromDate);
		final Binder.Binding<FromToModel, LocalDate> toBinding = fromToModelBinder.forField(toField)
				.withValidator(toRangeValidator).bind(FromToModel::getToDate, FromToModel::setToDate);

		fromField.addValueChangeListener(e -> {
			final LocalDate fromDate = e.getValue();
			toRangeValidator.setMinValue(fromDate);
			if (toField.getValue() != null) {
				toBinding.validate();
			}
		});
		toField.addValueChangeListener(e -> {
			final LocalDate toDate = e.getValue();
			fromRangeValidator.setMaxValue(toDate);
			if (fromField.getValue() != null) {
				fromBinding.validate();
			}
		});
		horizontalLayout.addComponents(fromField, toField);

		Label result = new Label();

		Button button = new Button("Show bean");
		button.addClickListener(event1 -> {
			final FromToModel bean = fromToModelBinder.getBean();
			result.setValue(bean.getFromDate() + " " + bean.getToDate());
		});
		horizontalLayout.addComponent(button);
		horizontalLayout.addComponent(result);

		setContent(horizontalLayout);
	}

	private static class FromToModel {

		private LocalDate fromDate;
		private LocalDate toDate;

		public LocalDate getFromDate() {
			return fromDate;
		}

		public void setFromDate(LocalDate fromDate) {
			this.fromDate = fromDate;
		}

		public LocalDate getToDate() {
			return toDate;
		}

		public void setToDate(LocalDate toDate) {
			this.toDate = toDate;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o)
				return true;
			if (!(o instanceof FromToModel))
				return false;
			FromToModel that = (FromToModel) o;
			return Objects.equals(getFromDate(), that.getFromDate()) && Objects.equals(getToDate(), that.getToDate());
		}

		@Override
		public int hashCode() {
			return Objects.hash(getFromDate(), getToDate());
		}
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}

```

**Comment by ZheSun88** [comment] 2018-11-15 09:39
Hi, 

Thanks for reporting this issue. But after some discussion, we realize that it is not a bug with the current implementation. The `validate()` call is not supposed to update the corresponding bean value. As it is stated in the Javadoc
```
     * <strong>Note:</strong> This method will attempt to temporarily apply all
     * current changes to the bean and run full bean validation for it. The
     * changes are reverted after bean validation.
     *
     * @return validation status for the binder
     */
    public BinderValidationStatus<BEAN> validate() {
```
We have added the same `note` section to the ` public BindingValidationStatus<TARGET> validate(boolean fireEvent);`, which is trying to make it more clear. 

For the example, you have provided, in order to make it work, you can change if statement of the event listener to `fromToModelBinder.writeBeanIfValid(fromToModelBinder.getBean());`, i.e.:
```java
fromField.addValueChangeListener(e -> {
            final LocalDate fromDate = e.getValue();
            toRangeValidator.setMinValue(fromDate);
            fromToModelBinder.writeBeanIfValid(fromToModelBinder.getBean());
        });
```

I hope that makes sense to you. 

Thank you and i am going to close this issue, once the javadoc fix is in.

**Closed** 2018-11-15 11:20 UTC
Labels: BFP, bug
