### ISSUE TITLE
Grid expanded columns resize to minimum (header) width if grid is reAttached

### ISSUE THREAD

**Issue by walindner** [vaadin/framework#9203] opened 2017-04-30 19:16 UTC
version 8.05

if the button is pressed in the following example, the width of column2 changes in a wrong way.
On browser window  resize the column width is corrected.

The grid can be reattached in different ways:
- wrapping layout is exchanged
- grid is placed on a tabsheet, user changes tabs
- ...

-----------------------------------------------------------------------
import com.vaadin.ui.*;

import java.util.stream.IntStream;

public class GridColumnSizing extends CustomComponent {

    private final Grid<Integer> grid;
    private final Button button = new Button("rebuild layout");

    public GridColumnSizing() {
        this.grid = new Grid<Integer>();
        this.grid.setSizeFull();
        this.grid.addColumn(i -> i)
                .setCaption("column1")
                .setWidth(100);

        this.grid.addColumn(i -> i / 2)
                .setCaption("column2")
                .setExpandRatio(1);
        fillItems();
        this.button.addClickListener(event -> rebuildLayout());
        rebuildLayout();
    }

    private void fillItems() {
        this.grid.setItems(IntStream.rangeClosed(1, 100).boxed());
    }

    private void rebuildLayout() {
        HorizontalLayout horizontalLayout = new HorizontalLayout();
        horizontalLayout.setSizeFull();
        horizontalLayout.addComponents(this.grid, this.button);
        setCompositionRoot(horizontalLayout);
    }
}

**Comment by TatuLund** [comment] 2018-05-04 13:29
Is this duplicate of https://github.com/vaadin/framework/issues/10438 ? If yes, this is fixed and should be closed.

**Closed** 2018-05-17 10:29 UTC
