### ISSUE TITLE
TwinColSelect doesn't select moved items after sorting items

### ISSUE THREAD

**Issue by Flaurite** [vaadin/framework#11287] opened 2018-11-01 10:25 UTC
- Vaadin Framework version: 8.5.1
- Description of the bug:
`TwinColSelect` doesn't select moved items after sorting. 

- Minimal reproducible example
1. Add to TwimColSelect some values, like in the image: 
![image](https://user-images.githubusercontent.com/22093943/48493407-2d961c80-e845-11e8-8d8a-1cebe83f2afd.png)

2. Select values: **Option 0**, **Option 5** and move them to **Selected Option**:
![image](https://user-images.githubusercontent.com/22093943/47846528-957a4b00-dde1-11e8-99ce-cf38da1c9cbc.png)
3. Return **Option 0**, **Option 5** to the **Available options**
![image](https://user-images.githubusercontent.com/22093943/47846562-bb9feb00-dde1-11e8-8b45-f76596eba233.png)

### **Expected result**
**Option 0** and **Option 5** should be selected after sorting items

![image](https://user-images.githubusercontent.com/22093943/48493865-27547000-e846-11e8-872f-13fddff32530.png)

### **Actual result**
**Option 4** and **Option 5** are selected.

**Comment by TatuLund** [comment] 2019-11-15 06:40
This seems to be duplicate of this one https://github.com/vaadin/framework/issues/1232

**Closed** 2019-11-19 09:04 UTC
Labels: bug
