### ISSUE TITLE
DateField.setValue does not work if some date is already typed in by the user

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#9763] opened 2017-08-01 16:03 UTC
Related to #9740

**Comment by ssindelar** [comment] 2017-08-08 10:49
Despite the error handling fixes in 8.1.1 setting the value of the Datefield on the server still doesn't clear the error message and validation still fails.

The problem is that AbstraftDateField.currentParseErrorMessage is not cleared. It should be cleared in doSetValue if a valid LocalDate (inside the Range) is set. currentParseErrorMessage is used by the "Default Validator" to check if the field is valid. Because the message still lingers around the validation thinks the value is invalid, despite being valid.

Also in 8.1.0 the cient had shown the value set by the server. Thats no longer the case in 8.1.1

**Comment by ssindelar** [comment] 2017-08-08 12:16
Also I noticed something other strange about DateField. When the user changes the Date from one invalid value to another invalid value the validation error disappers. Validating the Fields on the server afterwards still detects the invalid input but also doesn't mark it as invalid.

The fixes to the DateField in 8.1.1 seem to have broken some other functions of the field which makes it worse than before. 👎

**Comment by ssindelar** [comment] 2017-08-08 12:38
Example of brolen error indicator:
```
public class TestUi extends UI {
	private static final long serialVersionUID = 6146785985917164310L;

	@Override
	protected void init(VaadinRequest request) {

		DateField dateField = new DateField();
		setContent(dateField);
		Binder<TestUi> binder = new Binder<>();
		binder.forField(dateField)
				// always invalid
				.withValidator(o -> false, "invalid")
				// do nothing binding
				.bind(o -> null, (a, b) -> {
				});
		dateField.addValueChangeListener(event -> System.out.println("valid: " + binder.isValid()));
		dateField.setValue(LocalDate.now());
	}
}
```

Every Date should be invalid. The first date shown is correctly marked as invalid. Any change to the date removes the error indicator despite binder.isValid() returning false.

**Comment by tsuoanttila** [comment] 2017-10-16 13:22
Provided test code seems to already work with the changes to binder and datefield in `8.2.0.alpha2`

**Closed** 2017-10-20 06:54 UTC
Labels: bug
